"""
Curated DSA problem bank, one problem per curriculum day for Days 8-42
(Days 1-7 are Python drills, covered by study-notes/, not "problems" in
the DSA sense -- see docs/decisions.md; Days 43-45 are revision/mock
interviews and reuse problems already seeded here rather than adding new
ones). Every problem has real test cases, three real hints, and a real
reference solution.

Test case outputs are NOT hand-typed -- they are computed at seed time by
actually running `reference_solution` against `test_inputs`, so a typo in
an expected value can't silently ship. See init_db.py's seed_problems().
"""

PROBLEMS = [
    dict(slug="remove-duplicates-sorted", title="Remove Duplicates from Sorted Array",
         day=8, topic="arrays", pattern="read/write pointer", difficulty="Easy", interview_priority="Important", estimated_solve_minutes=15, progression_stage="core", canonical_reference="LeetCode 26: Remove Duplicates from Sorted Array",
         description="Given a sorted array `nums`, remove duplicates in place so each element appears only once, and return the number of unique elements. The relative order of unique elements must be kept, and this must be done in O(1) extra space.",
         constraints="1 <= len(nums) <= 3*10^4; nums is sorted in non-decreasing order.",
         function_signature="def remove_duplicates(nums):",
         starter_code="def remove_duplicates(nums):\n    # nums is sorted. Return the count of unique elements.\n    # Modify nums in place so nums[:count] holds the unique elements.\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(1)",
         brute_force_approach="Build a new list of unique elements, then copy back -- O(n) time but O(n) extra space, violating the constraint.",
         optimal_approach="Read/write pointer: write only advances when a genuinely new value is found (compare against nums[write-1]).",
         common_mistakes="Comparing against nums[read-1] instead of nums[write-1]; forgetting the array is already sorted so only adjacent duplicates matter.",
         edge_cases="Empty array; single element; all elements identical; no duplicates at all.",
         test_inputs=[([1,1,2],), ([0,0,1,1,1,2,2,3,3,4],), ([1],), ([],), ([5,5,5,5],)],
         reference_solution="def remove_duplicates(nums):\n    if not nums:\n        return 0\n    write = 1\n    for read in range(1, len(nums)):\n        if nums[read] != nums[write - 1]:\n            nums[write] = nums[read]\n            write += 1\n    return write\n",
         hints=["Think about two pointers moving through the array at different speeds -- one reads every element, one only advances when it finds something worth keeping.",
                "Compare each element at the read pointer against the LAST element already placed by the write pointer (nums[write-1]), not against nums[read-1].",
                "write = 1 to start (index 0 is always kept). For read in range(1, len(nums)): if nums[read] != nums[write-1]: place it at nums[write] and increment write. Return write."]),

    dict(slug="range-sum-prefix", title="Range Sum Query (Prefix Sum)",
         day=9, topic="arrays", pattern="prefix sum", difficulty="Easy", interview_priority="Important", estimated_solve_minutes=15, progression_stage="core", canonical_reference="LeetCode 303: Range Sum Query - Immutable",
         description="Given an integer array `nums`, implement `range_sum(nums, left, right)` that returns the sum of elements between indices left and right (inclusive), using a prefix sum so repeated queries are fast.",
         constraints="1 <= len(nums) <= 10^4; 0 <= left <= right < len(nums).",
         function_signature="def range_sum(nums, left, right):",
         starter_code="def range_sum(nums, left, right):\n    # Build a prefix sum array, then answer the query in O(1).\n    pass\n",
         expected_time_complexity="O(n) to build the prefix array, O(1) per query", expected_space_complexity="O(n)",
         brute_force_approach="Sum nums[left:right+1] directly each call -- O(n) per query.",
         optimal_approach="prefix[i] = sum of nums[0..i]. Then range sum = prefix[right] - prefix[left-1] (or prefix[right] if left==0).",
         common_mistakes="Off-by-one when left==0 (no prefix[-1] to subtract); rebuilding the prefix array on every call instead of once.",
         edge_cases="left == right (single element); left == 0; the whole array.",
         test_inputs=[([1,2,3,4,5], 1, 3), ([1,2,3,4,5], 0, 4), ([7], 0, 0), ([-2,4,6,-1], 1, 2)],
         reference_solution="def range_sum(nums, left, right):\n    prefix = [0] * len(nums)\n    prefix[0] = nums[0]\n    for i in range(1, len(nums)):\n        prefix[i] = prefix[i-1] + nums[i]\n    if left == 0:\n        return prefix[right]\n    return prefix[right] - prefix[left - 1]\n",
         hints=["Precompute a running total array where each position holds the sum of everything up to and including that index.",
                "A range sum from left to right equals prefix[right] minus everything before left, i.e. prefix[left-1] -- handle left==0 as a special case since there's no prefix[-1].",
                "prefix[0]=nums[0]; prefix[i]=prefix[i-1]+nums[i] for i>0. Then return prefix[right] if left==0 else prefix[right]-prefix[left-1]."]),

    dict(slug="valid-anagram", title="Valid Anagram",
         day=10, topic="strings", pattern="frequency comparison", difficulty="Easy", interview_priority="Important", estimated_solve_minutes=15, progression_stage="core", canonical_reference="LeetCode 242: Valid Anagram",
         description="Given two strings `s` and `t`, return True if `t` is an anagram of `s` (uses exactly the same characters, same counts), False otherwise.",
         constraints="1 <= len(s), len(t) <= 5*10^4; lowercase English letters.",
         function_signature="def is_anagram(s, t):",
         starter_code="def is_anagram(s, t):\n    pass\n",
         expected_time_complexity="O(n) with counting, O(n log n) with sorting", expected_space_complexity="O(1) (bounded alphabet) or O(n)",
         brute_force_approach="Sort both strings and compare -- O(n log n).",
         optimal_approach="Count character frequencies in one pass (or two, one +1 one -1) and compare -- O(n).",
         common_mistakes="Not checking len(s) != len(t) as a fast early exit; forgetting that anagram checks are case-sensitive unless stated otherwise.",
         edge_cases="Different lengths (immediately False); identical strings; single character.",
         test_inputs=[("anagram", "nagaram"), ("rat", "car"), ("a", "a"), ("ab", "a")],
         reference_solution="def is_anagram(s, t):\n    if len(s) != len(t):\n        return False\n    counts = {}\n    for ch in s:\n        counts[ch] = counts.get(ch, 0) + 1\n    for ch in t:\n        if ch not in counts:\n            return False\n        counts[ch] -= 1\n        if counts[ch] == 0:\n            del counts[ch]\n    return len(counts) == 0\n",
         hints=["Check the lengths first -- if they differ, they can't be anagrams, and you can return immediately.",
                "Count each character's frequency in the first string, then walk the second string subtracting from those counts.",
                "Use a dict: increment counts for every char in s, then decrement for every char in t. If any count would go negative or a char in t isn't in the dict, return False. At the end, all counts should be zero."]),

    dict(slug="two-sum", title="Two Sum", day=11, topic="hashing", pattern="hashmap lookup", difficulty="Easy", interview_priority="Core", estimated_solve_minutes=15, progression_stage="core", canonical_reference="LeetCode 1: Two Sum (NeetCode Arrays & Hashing)",
         description="Given an array of integers `nums` and an integer `target`, return the indices of the two numbers that add up to target. Assume exactly one solution exists, and you may not use the same element twice.",
         constraints="2 <= len(nums) <= 10^4; exactly one valid answer exists.",
         function_signature="def two_sum(nums, target):",
         starter_code="def two_sum(nums, target):\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(n)",
         brute_force_approach="Check every pair with nested loops -- O(n^2).",
         optimal_approach="Single pass with a hashmap of value->index; for each number check if its complement was already seen.",
         common_mistakes="Checking for the complement AFTER inserting the current number (can incorrectly match a number with itself); returning values instead of indices.",
         edge_cases="The two matching numbers are adjacent; negative numbers; the target requires the last two elements.",
         test_inputs=[([2,7,11,15], 9), ([3,2,4], 6), ([3,3], 6), ([-1,-2,-3,-4,-5], -8)],
         reference_solution="def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        complement = target - n\n        if complement in seen:\n            return [seen[complement], i]\n        seen[n] = i\n    return []\n",
         hints=["Instead of checking every pair, ask: as I scan left to right, have I already seen the number that would complete a pair with the current one?",
                "Store each number's index in a dict as you go. For the current number, compute target - number and check if THAT value is already a key in the dict.",
                "seen = {}; loop with enumerate; complement = target - n; if complement in seen: return [seen[complement], i]; else seen[n] = i."]),

    dict(slug="top-k-frequent", title="Top K Frequent Elements", day=12, topic="hashing", pattern="frequency + sort", difficulty="Medium", interview_priority="Important", estimated_solve_minutes=25, progression_stage="variation", canonical_reference="LeetCode 347: Top K Frequent Elements",
         description="Given an integer array `nums` and an integer `k`, return the k most frequent elements, in any order.",
         constraints="1 <= len(nums) <= 10^4; k is always valid (<= number of distinct elements).",
         function_signature="def top_k_frequent(nums, k):",
         starter_code="def top_k_frequent(nums, k):\n    pass\n",
         expected_time_complexity="O(n log n) with sorting (O(n log k) with a bounded heap, Day 34)", expected_space_complexity="O(n)",
         brute_force_approach="Count frequencies, sort all distinct values by count descending, take the first k.",
         optimal_approach="Same as brute force for now -- the heap-bounded O(n log k) version is Day 34's whole point.",
         common_mistakes="Sorting by the wrong key (value instead of frequency); forgetting ties can be broken arbitrarily since the problem allows any order.",
         edge_cases="k equals the number of distinct elements; all elements have the same frequency.",
         test_inputs=[([1,1,1,2,2,3], 2), ([1], 1), ([4,4,4,5,5,6], 1)],
         reference_solution="def top_k_frequent(nums, k):\n    counts = {}\n    for n in nums:\n        counts[n] = counts.get(n, 0) + 1\n    ordered = sorted(counts.keys(), key=lambda x: counts[x], reverse=True)\n    return sorted(ordered[:k])\n",
         comparison_mode="unordered_list",
         hints=["First figure out each number's frequency using a dict, exactly like Day 7's word-frequency exercise.",
                "Once you have frequencies, sort the distinct numbers by their frequency, descending, and take the first k.",
                "counts = {}; count each n. Then sorted(counts, key=lambda x: counts[x], reverse=True)[:k]. (Order doesn't matter -- the checker compares your result as a set.)"]),

    dict(slug="two-sum-sorted", title="Two Sum II (Sorted Input)", day=13, topic="two-pointer", pattern="opposite-direction two-pointer", difficulty="Easy", interview_priority="Core", estimated_solve_minutes=15, progression_stage="core", canonical_reference="LeetCode 167: Two Sum II - Input Array Is Sorted",
         description="Given a 1-indexed array of integers `numbers` sorted in non-decreasing order, find two numbers that add up to `target`. Return their 1-indexed positions as [index1, index2] with index1 < index2. You must use O(1) extra space.",
         constraints="2 <= len(numbers) <= 3*10^4; numbers is sorted ascending; exactly one solution exists.",
         function_signature="def two_sum_sorted(numbers, target):",
         starter_code="def two_sum_sorted(numbers, target):\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(1)",
         brute_force_approach="Nested loop over all pairs -- O(n^2), and doesn't use the fact that it's sorted.",
         optimal_approach="Two pointers from both ends: if the sum is too small move left forward, too big move right backward.",
         common_mistakes="Returning 0-indexed positions instead of 1-indexed; forgetting the array must already be sorted for this technique to work.",
         edge_cases="The answer is the first two elements; the answer is the last two elements; negative numbers.",
         test_inputs=[([2,7,11,15], 9), ([2,3,4], 6), ([-1,0], -1)],
         reference_solution="def two_sum_sorted(numbers, target):\n    left, right = 0, len(numbers) - 1\n    while left < right:\n        s = numbers[left] + numbers[right]\n        if s == target:\n            return [left + 1, right + 1]\n        elif s < target:\n            left += 1\n        else:\n            right -= 1\n    return []\n",
         hints=["Since the array is already sorted, think about starting pointers at both ends and moving them based on whether the current sum is too big or too small.",
                "If numbers[left]+numbers[right] < target, you need a bigger sum -- which pointer moves? If it's > target, you need a smaller sum.",
                "left, right = 0, len(numbers)-1; while left<right: compute sum; if equal return [left+1, right+1] (1-indexed!); if too small, left+=1; else right-=1."]),

    dict(slug="max-area-container", title="Container With Most Water", day=14, topic="two-pointer", pattern="same-direction greedy two-pointer", difficulty="Medium", interview_priority="Core", estimated_solve_minutes=25, progression_stage="variation", canonical_reference="LeetCode 11: Container With Most Water",
         description="Given an array `height` where height[i] is the height of a vertical line at position i, find two lines that together with the x-axis form a container holding the most water. Return the maximum area.",
         constraints="2 <= len(height) <= 10^5; 0 <= height[i] <= 10^4.",
         function_signature="def max_area(height):",
         starter_code="def max_area(height):\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(1)",
         brute_force_approach="Check every pair of lines -- O(n^2).",
         optimal_approach="Two pointers starting at both ends; always move the pointer at the SHORTER line inward, since that's the only move that could possibly increase the area.",
         common_mistakes="Moving the taller line's pointer (can never improve the result); using height[left]+height[right] instead of min() for the limiting height.",
         edge_cases="Only two lines; all lines the same height; strictly increasing or decreasing heights.",
         test_inputs=[([1,8,6,2,5,4,8,3,7],), ([1,1],), ([4,3,2,1,4],)],
         reference_solution="def max_area(height):\n    left, right = 0, len(height) - 1\n    best = 0\n    while left < right:\n        area = (right - left) * min(height[left], height[right])\n        best = max(best, area)\n        if height[left] < height[right]:\n            left += 1\n        else:\n            right -= 1\n    return best\n",
         hints=["Think of two pointers at the far ends of the array, and think about what happens to the area as you move one of them inward.",
                "Width always shrinks as you move inward, so the only way the area might grow is if the limiting (shorter) height increases -- which pointer should you move?",
                "left,right=0,len-1; area=(right-left)*min(height[left],height[right]); track the best; move whichever of left/right currently points at the SHORTER line."]),

    dict(slug="max-sum-subarray-k", title="Maximum Sum Subarray of Size K", day=15, topic="sliding-window", pattern="fixed-size window", difficulty="Easy", interview_priority="Core", estimated_solve_minutes=15, progression_stage="core", canonical_reference="Fixed-window pattern (cf. LeetCode 643: Maximum Average Subarray I)",
         description="Given an array `arr` and an integer `k`, find the maximum sum of any contiguous subarray of size exactly k.",
         constraints="1 <= k <= len(arr) <= 10^5.",
         function_signature="def max_sum_subarray(arr, k):",
         starter_code="def max_sum_subarray(arr, k):\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(1)",
         brute_force_approach="For each starting position, sum the next k elements -- O(n*k).",
         optimal_approach="Slide the window: subtract the element leaving, add the element entering, in O(1) per step.",
         common_mistakes="Recomputing sum(window) from scratch every slide (correct but O(n*k), defeats the purpose); off-by-one on the window's start/end indices.",
         edge_cases="k equals len(arr) (only one window); k == 1.",
         test_inputs=[([2,1,5,1,3,2], 3), ([1,2,3,4,5], 1), ([5,5,5], 3)],
         reference_solution="def max_sum_subarray(arr, k):\n    window_sum = sum(arr[:k])\n    best = window_sum\n    for i in range(k, len(arr)):\n        window_sum += arr[i] - arr[i - k]\n        best = max(best, window_sum)\n    return best\n",
         hints=["Rather than re-summing every window of size k from scratch, think about what changes when the window slides one step to the right.",
                "Only one element leaves the window (the leftmost) and one enters (the new rightmost) -- update the running sum with just those two changes.",
                "window_sum = sum(arr[:k]); best = window_sum; for i in range(k, len(arr)): window_sum += arr[i] - arr[i-k]; best = max(best, window_sum)."]),

    dict(slug="longest-unique-substring", title="Longest Substring Without Repeating Characters", day=16, topic="sliding-window", pattern="variable-size window", difficulty="Medium", interview_priority="Core", estimated_solve_minutes=25, progression_stage="variation", canonical_reference="LeetCode 3: Longest Substring Without Repeating Characters",
         description="Given a string `s`, find the length of the longest substring without repeating characters.",
         constraints="0 <= len(s) <= 5*10^4.",
         function_signature="def longest_unique_substring(s):",
         starter_code="def longest_unique_substring(s):\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(min(n, alphabet size))",
         brute_force_approach="Check every substring for uniqueness -- O(n^3) or O(n^2) with a set.",
         optimal_approach="Variable-size sliding window with a dict tracking the last seen index of each character; jump `left` past a repeat when found.",
         common_mistakes="Jumping left backward instead of forward when a repeat is found outside the current window; forgetting to update best AFTER adjusting left.",
         edge_cases="Empty string; all characters identical; all characters unique.",
         test_inputs=[("abcabcbb",), ("bbbbb",), ("pwwkew",), ("",)],
         reference_solution="def longest_unique_substring(s):\n    seen = {}\n    left = 0\n    best = 0\n    for right, ch in enumerate(s):\n        if ch in seen and seen[ch] >= left:\n            left = seen[ch] + 1\n        seen[ch] = right\n        best = max(best, right - left + 1)\n    return best\n",
         hints=["Use a window defined by two pointers, and a dict remembering the last index each character was seen at.",
                "When you see a character that's already in the dict AND its last position is inside the current window, you must shrink the window by moving left past that old occurrence.",
                "seen={}; left=0; best=0; for right,ch in enumerate(s): if ch in seen and seen[ch]>=left: left=seen[ch]+1; seen[ch]=right; best=max(best,right-left+1)."]),

    dict(slug="bubble-sort", title="Implement Bubble Sort", day=17, topic="sorting", pattern="comparison sort", difficulty="Easy", interview_priority="Optional", estimated_solve_minutes=15, progression_stage="core", canonical_reference="Classic algorithm -- CS fundamentals, not a typical standalone interview question",
         description="Implement bubble sort: repeatedly step through the array, compare adjacent elements, and swap them if out of order, until the array is sorted. Return the sorted array.",
         constraints="0 <= len(arr) <= 10^3.",
         function_signature="def bubble_sort(arr):",
         starter_code="def bubble_sort(arr):\n    pass\n",
         expected_time_complexity="O(n^2), O(n) best case with early exit", expected_space_complexity="O(1)",
         brute_force_approach="This IS the baseline algorithm -- there's no simpler brute force.",
         optimal_approach="Track whether any swap happened in a pass; if not, the array is already sorted and you can stop early.",
         common_mistakes="Forgetting the early-exit optimization; off-by-one in the inner loop's upper bound (should shrink each pass).",
         edge_cases="Empty array; already sorted array; reverse-sorted array; duplicates.",
         test_inputs=[([5,2,4,1,3],), ([],), ([1],), ([3,3,2,2,1],)],
         reference_solution="def bubble_sort(arr):\n    arr = arr[:]\n    n = len(arr)\n    for i in range(n):\n        swapped = False\n        for j in range(n - i - 1):\n            if arr[j] > arr[j+1]:\n                arr[j], arr[j+1] = arr[j+1], arr[j]\n                swapped = True\n        if not swapped:\n            break\n    return arr\n",
         hints=["Repeatedly scan the array comparing each pair of neighbors, swapping them if they're in the wrong order -- do this for as many passes as needed.",
                "Each full pass guarantees the largest remaining unsorted element 'bubbles' to its correct position at the end -- so each pass can scan one element less than the last.",
                "for i in range(n): swapped=False; for j in range(n-i-1): if arr[j]>arr[j+1]: swap, swapped=True; if not swapped: break (already sorted)."]),

    dict(slug="insertion-sort", title="Implement Insertion Sort", day=18, topic="sorting", pattern="comparison sort", difficulty="Easy", interview_priority="Optional", estimated_solve_minutes=15, progression_stage="variation", canonical_reference="Classic algorithm -- CS fundamentals, not a typical standalone interview question",
         description="Implement insertion sort: build the sorted portion of the array one element at a time by inserting each new element into its correct position among the already-sorted elements. Return the sorted array.",
         constraints="0 <= len(arr) <= 10^3.",
         function_signature="def insertion_sort(arr):",
         starter_code="def insertion_sort(arr):\n    pass\n",
         expected_time_complexity="O(n^2) worst case, O(n) if nearly sorted", expected_space_complexity="O(1)",
         brute_force_approach="No simpler brute force -- this is the baseline algorithm.",
         optimal_approach="Shift larger elements right to make room, rather than swapping pairwise repeatedly.",
         common_mistakes="Off-by-one on the shifting loop's boundary; forgetting to place `key` after the shifting loop ends.",
         edge_cases="Empty array; single element; already sorted; all duplicates.",
         test_inputs=[([12,11,13,5,6],), ([],), ([1],), ([2,2,2],)],
         reference_solution="def insertion_sort(arr):\n    arr = arr[:]\n    for i in range(1, len(arr)):\n        key = arr[i]\n        j = i - 1\n        while j >= 0 and arr[j] > key:\n            arr[j+1] = arr[j]\n            j -= 1\n        arr[j+1] = key\n    return arr\n",
         hints=["Think of sorting a hand of playing cards: keep a sorted portion on the left, and insert each new card into its correct spot among the ones you've already sorted.",
                "To insert the current element, shift every larger element in the sorted portion one spot to the right to make room, rather than doing pairwise swaps.",
                "for i in range(1,len): key=arr[i]; j=i-1; while j>=0 and arr[j]>key: arr[j+1]=arr[j]; j-=1; arr[j+1]=key."]),

    dict(slug="merge-sort", title="Implement Merge Sort", day=19, topic="sorting", pattern="divide and conquer", difficulty="Medium", interview_priority="Core", estimated_solve_minutes=30, progression_stage="core", canonical_reference="Classic algorithm; frequently asked as 'implement merge sort'",
         description="Implement merge sort: recursively split the array in half, sort each half, then merge the two sorted halves back together. Return the sorted array.",
         constraints="0 <= len(arr) <= 10^4.",
         function_signature="def merge_sort(arr):",
         starter_code="def merge_sort(arr):\n    pass\n",
         expected_time_complexity="O(n log n)", expected_space_complexity="O(n)",
         brute_force_approach="A comparison sort like bubble/insertion sort achieves the same result at O(n^2).",
         optimal_approach="Divide and conquer: split, recursively sort each half, merge. The merge step is O(n) per level, with O(log n) levels.",
         common_mistakes="Missing the base case (length <= 1), causing infinite recursion; off-by-one on the midpoint; mishandling leftover elements when one half empties first during merge.",
         edge_cases="Empty array; single element; already sorted; reverse sorted; duplicates.",
         test_inputs=[([5,2,4,1,3],), ([],), ([1],), ([9,8,7,6,5,4,3,2,1],)],
         reference_solution="def merge_sort(arr):\n    if len(arr) <= 1:\n        return arr[:]\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    result, i, j = [], 0, 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i]); i += 1\n        else:\n            result.append(right[j]); j += 1\n    return result + left[i:] + right[j:]\n",
         hints=["Split the array in half, recursively sort each half (this is where the recursion from Day 23 will feel familiar once you reach it -- for now, trust that sorting a smaller array works the same way), then merge them.",
                "The merge step walks both sorted halves with two pointers, always taking the smaller of the two current elements, then appends whatever's left over from either side.",
                "if len(arr)<=1: return arr. Otherwise split at mid, recursively sort both halves, then merge with two pointers comparing left[i] and right[j]."]),

    dict(slug="quicksort", title="Implement Quicksort", day=20, topic="sorting", pattern="divide and conquer, partitioning", difficulty="Medium", interview_priority="Core", estimated_solve_minutes=30, progression_stage="variation", canonical_reference="Classic algorithm; frequently asked as 'implement quicksort / the partition step'",
         description="Implement quicksort: pick a pivot, partition the array into elements less than, equal to, and greater than the pivot, and recursively sort the partitions. Return the sorted array.",
         constraints="0 <= len(arr) <= 10^4.",
         function_signature="def quicksort(arr):",
         starter_code="def quicksort(arr):\n    pass\n",
         expected_time_complexity="O(n log n) average, O(n^2) worst case", expected_space_complexity="O(n) with this list-comprehension style (O(log n) with in-place partitioning)",
         brute_force_approach="Any O(n^2) comparison sort achieves correctness without the pivot idea.",
         optimal_approach="Partition around a pivot each recursive call; a well-chosen pivot (e.g. middle element) keeps partitions balanced.",
         common_mistakes="Always choosing the first element as pivot on already-sorted input (worst case every time); forgetting to handle the 'equal to pivot' bucket, which matters when there are duplicates.",
         edge_cases="Empty array; single element; all duplicates; already sorted (worst case for a naive pivot choice).",
         test_inputs=[([3,6,8,10,1,2,1],), ([],), ([1],), ([5,5,5,5],)],
         reference_solution="def quicksort(arr):\n    if len(arr) <= 1:\n        return arr[:]\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    mid = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quicksort(left) + mid + quicksort(right)\n",
         hints=["Pick one element as a 'pivot', then split the rest of the array into things smaller than it and things larger than it.",
                "Recursively sort each of those two partitions the same way, then concatenate: sorted-smaller + pivot(s) + sorted-larger.",
                "pivot = arr[len(arr)//2]; left = [x for x in arr if x<pivot]; mid = [x for x in arr if x==pivot]; right = [x for x in arr if x>pivot]; return quicksort(left)+mid+quicksort(right)."]),

    dict(slug="binary-search", title="Binary Search", day=21, topic="binary-search", pattern="classic binary search", difficulty="Easy", interview_priority="Core", estimated_solve_minutes=15, progression_stage="core", canonical_reference="LeetCode 704: Binary Search",
         description="Given a sorted array `nums` and a `target`, return the index of target if it exists, otherwise -1. Must run in O(log n).",
         constraints="1 <= len(nums) <= 10^4; nums sorted ascending, all unique.",
         function_signature="def binary_search(nums, target):",
         starter_code="def binary_search(nums, target):\n    pass\n",
         expected_time_complexity="O(log n)", expected_space_complexity="O(1)",
         brute_force_approach="Scan linearly -- O(n), doesn't use the sorted property.",
         optimal_approach="Repeatedly halve the search space by comparing the target to the middle element.",
         common_mistakes="low<=high vs low<high confusion (using the wrong one causes missed matches or infinite loops); off-by-one on low=mid+1/high=mid-1.",
         edge_cases="Target not present; target is the first or last element; single-element array.",
         test_inputs=[([-1,0,3,5,9,12], 9), ([-1,0,3,5,9,12], 2), ([5], 5), ([5], -5)],
         reference_solution="def binary_search(nums, target):\n    low, high = 0, len(nums) - 1\n    while low <= high:\n        mid = low + (high - low) // 2\n        if nums[mid] == target:\n            return mid\n        elif nums[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1\n",
         hints=["Since the array is sorted, you can eliminate half the remaining possibilities with each comparison instead of checking one element at a time.",
                "Keep a low and high boundary. Look at the middle element: if it's the target, you're done; if it's too small, the target must be to the right; if too big, to the left.",
                "low,high=0,len-1; while low<=high: mid=low+(high-low)//2; compare nums[mid] to target and narrow low or high accordingly; return -1 if the loop ends without a match."]),

    dict(slug="search-rotated-sorted", title="Search in Rotated Sorted Array", day=22, topic="binary-search", pattern="binary search variant", difficulty="Medium", interview_priority="Core", estimated_solve_minutes=25, progression_stage="variation", canonical_reference="LeetCode 33: Search in Rotated Sorted Array",
         description="Given a rotated sorted array `nums` (e.g. [4,5,6,7,0,1,2]) with all unique values, and a `target`, return its index or -1. Must run in O(log n).",
         constraints="1 <= len(nums) <= 5000; all values unique; nums was originally sorted then rotated at an unknown pivot.",
         function_signature="def search_rotated(nums, target):",
         starter_code="def search_rotated(nums, target):\n    pass\n",
         expected_time_complexity="O(log n)", expected_space_complexity="O(1)",
         brute_force_approach="Linear scan -- O(n), ignores the sorted-but-rotated structure.",
         optimal_approach="At each step, one half (low..mid or mid..high) is guaranteed normally sorted; determine which, then check if target falls in that half's range.",
         common_mistakes="Using strict < instead of <= when comparing nums[low] and nums[mid] to decide which half is sorted; off-by-one on the range check.",
         edge_cases="Target at the rotation point; array not actually rotated (fully sorted); single element; target not present.",
         test_inputs=[([4,5,6,7,0,1,2], 0), ([4,5,6,7,0,1,2], 3), ([1], 0), ([1], 1)],
         reference_solution="def search_rotated(nums, target):\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[lo] <= nums[mid]:\n            if nums[lo] <= target < nums[mid]:\n                hi = mid - 1\n            else:\n                lo = mid + 1\n        else:\n            if nums[mid] < target <= nums[hi]:\n                lo = mid + 1\n            else:\n                hi = mid - 1\n    return -1\n",
         hints=["Even though the whole array isn't sorted, at least one of the two halves around any midpoint always is -- figure out which one.",
                "Compare nums[lo] to nums[mid]: if nums[lo] <= nums[mid], the left half is normally sorted, so you can easily check if target falls in that range; otherwise the right half is.",
                "Standard binary search skeleton, but instead of just comparing to nums[mid], first determine which half is sorted, then check if target is within that sorted half's value range to decide which way to move lo/hi."]),

    dict(slug="factorial-recursive", title="Factorial (Recursive)", day=23, topic="recursion", pattern="base case + recursive case", difficulty="Easy", interview_priority="Optional", estimated_solve_minutes=10, progression_stage="core", canonical_reference="Original beginner exercise -- recursion warm-up, not a standalone interview question",
         description="Implement factorial(n) recursively (not with a loop): n! = n * (n-1) * ... * 1, with 0! = 1.",
         constraints="0 <= n <= 20.",
         function_signature="def factorial(n):",
         starter_code="def factorial(n):\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(n) call stack depth",
         brute_force_approach="An iterative loop achieves the same result without recursion -- fine, but the point of this exercise is the recursive pattern itself.",
         optimal_approach="Base case n<=1 returns 1; recursive case returns n * factorial(n-1).",
         common_mistakes="Missing the base case entirely (infinite recursion / RecursionError); forgetting to return the recursive call's result.",
         edge_cases="n=0 (should be 1); n=1.",
         test_inputs=[(5,), (0,), (1,), (10,)],
         reference_solution="def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n",
         hints=["Every recursive function needs a case simple enough to answer directly without recursing further -- what's the simplest factorial you already know the answer to?",
                "For anything bigger than the base case, express the answer in terms of a SMALLER version of the same problem: n! in terms of (n-1)!.",
                "if n<=1: return 1. Otherwise: return n * factorial(n-1)."]),

    dict(slug="subsets", title="Subsets", day=24, topic="recursion", pattern="backtracking", difficulty="Medium", interview_priority="Core", estimated_solve_minutes=30, progression_stage="variation", canonical_reference="LeetCode 78: Subsets",
         description="Given an array `nums` of unique integers, return all possible subsets (the power set), as a list of lists, in any order.",
         constraints="1 <= len(nums) <= 10.",
         function_signature="def subsets(nums):",
         starter_code="def subsets(nums):\n    pass\n",
         expected_time_complexity="O(n * 2^n)", expected_space_complexity="O(n * 2^n) for the output",
         brute_force_approach="This IS close to the only reasonable approach -- there are inherently 2^n subsets to produce.",
         optimal_approach="Backtracking: for each element, recursively explore both 'include it' and 'exclude it' (or equivalently, build up paths and record every path).",
         common_mistakes="Appending `path` directly to results instead of `path[:]` (a copy) -- later mutations then corrupt already-saved subsets; forgetting to pop() after each recursive call.",
         edge_cases="Single-element array; the empty subset must be included.",
         test_inputs=[([1,2,3],), ([0],)],
         reference_solution="def subsets(nums):\n    result = []\n    def backtrack(start, path):\n        result.append(path[:])\n        for i in range(start, len(nums)):\n            path.append(nums[i])\n            backtrack(i + 1, path)\n            path.pop()\n    backtrack(0, [])\n    return result\n",
         comparison_mode="unordered_list_of_lists",
         hints=["At each position, you have a binary choice: include this element in the current subset, or don't. Explore both.",
                "Record the current path (a copy of it!) as a valid subset at every step of the recursion, not just at the end -- every prefix is itself a valid subset.",
                "backtrack(start, path): result.append(path[:]); for i in range(start, len(nums)): path.append(nums[i]); backtrack(i+1, path); path.pop(). (Order doesn't matter -- the checker compares the set of subsets.)"]),

    dict(slug="reverse-linked-list", title="Reverse Linked List", day=27, topic="linked-lists", pattern="three-pointer reversal", difficulty="Easy", interview_priority="Core", estimated_solve_minutes=15, progression_stage="core", canonical_reference="LeetCode 206: Reverse Linked List",
         description="Given the head of a singly linked list, reverse it and return the new head. The list is represented as a Python list here for testing; your function receives it as a list and should return the reversed list (simulating pointer reversal logic internally is the point -- see starter code).",
         constraints="0 <= length <= 5000.",
         function_signature="def reverse_list(values):",
         starter_code="class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None\n\ndef build_list(values):\n    head = None\n    for v in reversed(values):\n        node = Node(v)\n        node.next = head\n        head = node\n    return head\n\ndef to_list(head):\n    result = []\n    while head:\n        result.append(head.val)\n        head = head.next\n    return result\n\ndef reverse_list(values):\n    # Build a real linked list from `values`, reverse it using the\n    # three-pointer technique, then convert back to a plain list to return.\n    head = build_list(values)\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(1) extra (excluding the list itself)",
         brute_force_approach="Collect all values into a Python list, reverse that list, then rebuild -- works but doesn't practice real pointer manipulation.",
         optimal_approach="Three pointers (prev, curr, next): walk forward, flipping each node's .next to point backward.",
         common_mistakes="Overwriting curr.next before saving it, losing the rest of the list; off-by-one dropping the last node.",
         edge_cases="Empty list; single-element list.",
         test_inputs=[([1,2,3,4,5],), ([],), ([1],), ([1,2],)],
         reference_solution="class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None\n\ndef build_list(values):\n    head = None\n    for v in reversed(values):\n        node = Node(v)\n        node.next = head\n        head = node\n    return head\n\ndef to_list(head):\n    result = []\n    while head:\n        result.append(head.val)\n        head = head.next\n    return result\n\ndef reverse_list(values):\n    head = build_list(values)\n    prev = None\n    curr = head\n    while curr:\n        nxt = curr.next\n        curr.next = prev\n        prev = curr\n        curr = nxt\n    return to_list(prev)\n",
         hints=["Walk the list with a pointer, and at each node flip its .next to point to the PREVIOUS node instead of the next one.",
                "You need three pointers in play at once: the previous node (starts as None), the current node, and a temporary that remembers 'next' before you overwrite curr.next.",
                "prev, curr = None, head; while curr: nxt = curr.next; curr.next = prev; prev = curr; curr = nxt. Return prev at the end (it's the new head)."]),

    dict(slug="valid-parentheses", title="Valid Parentheses", day=28, topic="stacks", pattern="matching with a stack", difficulty="Easy", interview_priority="Core", estimated_solve_minutes=15, progression_stage="core", canonical_reference="LeetCode 20: Valid Parentheses",
         description="Given a string `s` containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid (every open bracket is closed by the same type, in the correct order).",
         constraints="1 <= len(s) <= 10^4.",
         function_signature="def is_valid_parens(s):",
         starter_code="def is_valid_parens(s):\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(n)",
         brute_force_approach="No simpler approach exists -- a stack is the natural and standard solution.",
         optimal_approach="Push opening brackets; on a closing bracket, pop and check it matches; string is valid iff the stack is empty at the end.",
         common_mistakes="Popping from an empty stack without checking first (crashes); forgetting to verify the stack is empty at the very end (catches unmatched opens like '((').",
         edge_cases="Empty string is arguably invalid per most definitions (test uses non-empty); a string of only closing brackets; a string of only opening brackets.",
         test_inputs=[("()",), ("()[]{}",), ("(]",), ("([)]",), ("{[]}",)],
         reference_solution="def is_valid_parens(s):\n    stack = []\n    pairs = {')': '(', ']': '[', '}': '{'}\n    for ch in s:\n        if ch in '([{':\n            stack.append(ch)\n        elif ch in pairs:\n            if not stack or stack.pop() != pairs[ch]:\n                return False\n    return not stack\n",
         hints=["Nested structures are exactly what a LIFO (last-in-first-out) structure is good at matching -- think about what to do on an opening bracket vs a closing one.",
                "On an opening bracket, push it. On a closing bracket, it must match whatever's currently on top of the stack -- if it doesn't (or the stack is empty), the string is invalid.",
                "stack=[]; on open bracket push it; on close bracket, if stack is empty or stack.pop() doesn't match, return False. At the end, return True only if the stack is empty."]),

    dict(slug="binary-tree-level-order", title="Binary Tree Level Order Traversal", day=32, topic="trees", pattern="BFS with a queue", difficulty="Medium", interview_priority="Core", estimated_solve_minutes=25, progression_stage="variation", canonical_reference="LeetCode 102: Binary Tree Level Order Traversal",
         description="Given the root of a binary tree (represented here as a nested list [val, left, right] or None), return its level-order traversal as a flat list of values (queue processing order).",
         constraints="0 <= number of nodes <= 2000.",
         function_signature="def level_order(tree):",
         starter_code="class TreeNode:\n    def __init__(self, val, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef build_tree(spec):\n    # spec is [val, left_spec, right_spec] or None\n    if spec is None:\n        return None\n    val, left_spec, right_spec = spec\n    return TreeNode(val, build_tree(left_spec), build_tree(right_spec))\n\ndef level_order(tree):\n    root = build_tree(tree)\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(n)",
         brute_force_approach="Recursive DFS tracking depth, grouping by depth afterward -- works but obscures the natural queue-based approach.",
         optimal_approach="BFS with a queue: process a node, then enqueue its children, giving level-by-level order for free.",
         common_mistakes="Using a stack instead of a queue (produces a different, DFS-like order); forgetting to check for None children before enqueueing.",
         edge_cases="Empty tree (None); single node; a tree that's just a left (or right) chain.",
         test_inputs=[([3,[9,None,None],[20,[15,None,None],[7,None,None]]],), (None,), ([1,None,None],)],
         reference_solution="from collections import deque\n\nclass TreeNode:\n    def __init__(self, val, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef build_tree(spec):\n    if spec is None:\n        return None\n    val, left_spec, right_spec = spec\n    return TreeNode(val, build_tree(left_spec), build_tree(right_spec))\n\ndef level_order(tree):\n    root = build_tree(tree)\n    if not root:\n        return []\n    result, queue = [], deque([root])\n    while queue:\n        node = queue.popleft()\n        result.append(node.val)\n        if node.left:\n            queue.append(node.left)\n        if node.right:\n            queue.append(node.right)\n    return result\n",
         hints=["Think about processing nodes in the exact order they're discovered -- what data structure gives you that (first discovered, first processed)?",
                "Use a queue: pop a node, record its value, then push its children (if they exist) onto the back of the queue.",
                "from collections import deque; queue=deque([root]); while queue: node=queue.popleft(); append node.val; enqueue node.left/right if not None."]),

    dict(slug="kth-largest-stream", title="Kth Largest Element in a Stream", day=33, topic="heaps", pattern="bounded min-heap", difficulty="Easy", interview_priority="Important", estimated_solve_minutes=20, progression_stage="core", canonical_reference="LeetCode 703: Kth Largest Element in a Stream",
         description="Design a class-free function `kth_largest_sequence(nums, k)` that, given a starting list of numbers and k, simulates adding each number in `nums` one at a time and returns a list of the current kth-largest value after each addition (once at least k numbers have been added; earlier entries can be None).",
         constraints="1 <= k <= len(nums) <= 10^4.",
         function_signature="def kth_largest_sequence(nums, k):",
         starter_code="import heapq\n\ndef kth_largest_sequence(nums, k):\n    pass\n",
         expected_time_complexity="O(n log k)", expected_space_complexity="O(k)",
         brute_force_approach="After each addition, sort everything seen so far and pick the kth largest -- O(n^2 log n) overall.",
         optimal_approach="Maintain a min-heap of size k holding the k largest values seen; its smallest element (the heap's root) IS the kth largest.",
         common_mistakes="Forgetting to pop when the heap exceeds size k (heap grows unbounded, losing the whole point); confusing 'kth largest' with 'kth smallest'.",
         edge_cases="Fewer than k numbers added so far (return None for those positions); duplicate values.",
         test_inputs=[([4,5,8,2], 3), ([1,2,3,4,5], 1)],
         reference_solution="import heapq\n\ndef kth_largest_sequence(nums, k):\n    heap = []\n    result = []\n    for n in nums:\n        heapq.heappush(heap, n)\n        if len(heap) > k:\n            heapq.heappop(heap)\n        result.append(heap[0] if len(heap) == k else None)\n    return result\n",
         hints=["A min-heap of a FIXED size k has a useful property: its smallest element is exactly the kth largest of everything you've put into it, as long as you only ever keep the k largest.",
                "Push every new number in, but if the heap grows past size k, pop the smallest -- that keeps only the k largest values seen so far.",
                "heap=[]; for n in nums: heappush(heap, n); if len(heap)>k: heappop(heap); record heap[0] if len(heap)==k else None."]),

    dict(slug="number-of-islands", title="Number of Islands (BFS)", day=36, topic="graphs", pattern="grid BFS", difficulty="Medium", interview_priority="Core", estimated_solve_minutes=25, progression_stage="core", canonical_reference="LeetCode 200: Number of Islands",
         description="Given a 2D grid of '1' (land) and '0' (water), return the number of islands (connected groups of land, connected horizontally or vertically).",
         constraints="1 <= rows, cols <= 300.",
         function_signature="def num_islands(grid):",
         starter_code="from collections import deque\n\ndef num_islands(grid):\n    pass\n",
         expected_time_complexity="O(rows * cols)", expected_space_complexity="O(rows * cols)",
         brute_force_approach="No meaningfully simpler approach -- you must visit every land cell at least once.",
         optimal_approach="For each unvisited land cell, BFS (or DFS) outward marking every connected land cell visited, counting one island per BFS started.",
         common_mistakes="Forgetting to check grid boundaries before visiting a neighbor (IndexError); mutating the grid without a separate visited set AND forgetting that counts as \"marking visited\" too (either approach works, but pick one consistently).",
         edge_cases="All water (0 islands); all land (1 island); grid with a single cell.",
         test_inputs=[([["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]],),
                      ([["0","0"],["0","0"]],)],
         reference_solution="from collections import deque\n\ndef num_islands(grid):\n    if not grid:\n        return 0\n    rows, cols = len(grid), len(grid[0])\n    visited = [[False]*cols for _ in range(rows)]\n    count = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == '1' and not visited[r][c]:\n                count += 1\n                q = deque([(r, c)])\n                visited[r][c] = True\n                while q:\n                    cr, cc = q.popleft()\n                    for dr, dc in [(1,0),(-1,0),(0,1),(0,-1)]:\n                        nr, nc = cr+dr, cc+dc\n                        if 0 <= nr < rows and 0 <= nc < cols and not visited[nr][nc] and grid[nr][nc] == '1':\n                            visited[nr][nc] = True\n                            q.append((nr, nc))\n    return count\n",
         hints=["Think of each grid cell as a graph node, and each cell's up/down/left/right land neighbors as its edges.",
                "Scan every cell; whenever you find unvisited land, that's the start of a NEW island -- run a BFS from there to mark every connected land cell as visited, then increment your island count.",
                "For each cell, if it's land and unvisited: count+=1, then BFS from it (queue, mark visited, check the 4 neighbors are in-bounds and unvisited land before enqueueing)."]),

    dict(slug="network-delay-time", title="Network Delay Time (Dijkstra)", day=38, topic="graphs", pattern="Dijkstra's algorithm", difficulty="Medium", interview_priority="Important", estimated_solve_minutes=30, progression_stage="variation", canonical_reference="LeetCode 743: Network Delay Time",
         description="You are given `times`, a list of directed edges [u, v, w] meaning a signal from u to v takes w time, `n` nodes labeled 1..n, and a starting node `k`. Return the time it takes for a signal starting at k to reach all n nodes, or -1 if impossible.",
         constraints="1 <= n <= 100; 1 <= len(times) <= 6000; all weights positive.",
         function_signature="def network_delay_time(times, n, k):",
         starter_code="import heapq\n\ndef network_delay_time(times, n, k):\n    pass\n",
         expected_time_complexity="O((V+E) log V)", expected_space_complexity="O(V+E)",
         brute_force_approach="Try all orderings of visiting nodes -- exponential, impractical.",
         optimal_approach="Dijkstra's algorithm: always expand the currently-closest unvisited node next using a min-heap; the answer is the max over all shortest distances (or -1 if any node is unreachable).",
         common_mistakes="Using a plain queue/BFS instead of a heap (silently gives wrong answers on weighted edges); forgetting to skip a heap entry whose distance is stale (already improved elsewhere).",
         edge_cases="A node unreachable from k (-1); n=1 (trivially 0); multiple edges between the same pair with different weights.",
         test_inputs=[([[2,1,1],[2,3,1],[3,4,1]], 4, 2), ([[1,2,1]], 2, 1), ([[1,2,1]], 2, 2)],
         reference_solution="import heapq\n\ndef network_delay_time(times, n, k):\n    graph = {}\n    for u, v, w in times:\n        graph.setdefault(u, []).append((v, w))\n    dist = {}\n    heap = [(0, k)]\n    while heap:\n        d, node = heapq.heappop(heap)\n        if node in dist:\n            continue\n        dist[node] = d\n        for neighbor, w in graph.get(node, []):\n            if neighbor not in dist:\n                heapq.heappush(heap, (d + w, neighbor))\n    if len(dist) != n:\n        return -1\n    return max(dist.values())\n",
         hints=["Build an adjacency list from the edges first, then think about how BFS's 'expand the queue in discovery order' needs to change when edges have different costs.",
                "Use a min-heap keyed by distance-so-far instead of a plain queue, always expanding the currently-closest unvisited node next -- once a node is finalized (popped for the first time), its distance is correct and won't improve.",
                "Build graph; heap=[(0,k)]; dist={}; while heap: pop (d,node); if node already in dist, skip (stale entry); else record dist[node]=d and push neighbors with d+weight. At the end, if not all n nodes have a distance, return -1, else return the max distance."]),

    dict(slug="climbing-stairs", title="Climbing Stairs", day=40, topic="dynamic-programming", pattern="1D DP", difficulty="Easy", interview_priority="Core", estimated_solve_minutes=15, progression_stage="core", canonical_reference="LeetCode 70: Climbing Stairs",
         description="You're climbing a staircase with `n` steps. Each move you can climb 1 or 2 steps. Return the number of distinct ways to reach the top.",
         constraints="1 <= n <= 45.",
         function_signature="def climb_stairs(n):",
         starter_code="def climb_stairs(n):\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(1)",
         brute_force_approach="Naive recursion trying both choices (1 or 2 steps) at every position -- O(2^n), massively redundant (it's exactly Fibonacci in disguise).",
         optimal_approach="dp[i] = dp[i-1] + dp[i-2] (ways to reach step i = ways to reach i-1, plus one more step, or ways to reach i-2, plus two more steps). Track only the last two values.",
         common_mistakes="Off-by-one on the base cases (dp[1]=1, dp[2]=2, not starting from 0 incorrectly); rederiving this as if it were unrelated to Fibonacci instead of recognizing the same recurrence.",
         edge_cases="n=1 (only 1 way); n=2 (2 ways: 1+1 or 2).",
         test_inputs=[(2,), (3,), (1,), (5,)],
         reference_solution="def climb_stairs(n):\n    if n <= 2:\n        return n\n    prev2, prev1 = 1, 2\n    for _ in range(3, n + 1):\n        prev2, prev1 = prev1, prev1 + prev2\n    return prev1\n",
         hints=["To reach step n, your last move was either a 1-step from step n-1, or a 2-step from step n-2 -- so the total ways to reach n is the sum of ways to reach each of those.",
                "This recurrence -- dp[i] = dp[i-1] + dp[i-2] -- should look familiar from Day 39's Fibonacci; you don't need a full array, just the last two values.",
                "if n<=2: return n. Otherwise iterate from 3 to n keeping prev2, prev1 = prev1, prev1+prev2, and return prev1 at the end."]),

    dict(slug="coin-change", title="Coin Change (Minimum Coins)", day=41, topic="dynamic-programming", pattern="1D DP, minimization", difficulty="Medium", interview_priority="Core", estimated_solve_minutes=30, progression_stage="variation", canonical_reference="LeetCode 322: Coin Change",
         description="Given `coins` (available denominations) and an `amount`, return the fewest number of coins needed to make up that amount, or -1 if it's not possible.",
         constraints="1 <= len(coins) <= 12; 0 <= amount <= 10^4.",
         function_signature="def coin_change(coins, amount):",
         starter_code="def coin_change(coins, amount):\n    pass\n",
         expected_time_complexity="O(amount * len(coins))", expected_space_complexity="O(amount)",
         brute_force_approach="Try every combination of coins recursively -- exponential.",
         optimal_approach="dp[a] = minimum coins to make amount a; for each amount, try every coin and take the best resulting dp[a-coin]+1.",
         common_mistakes="Initializing dp to 0 instead of infinity (falsely implies every amount is trivially reachable); not checking c <= a before using dp[a-c].",
         edge_cases="amount=0 (0 coins needed); amount not reachable with given coins (-1); a coin exactly equal to amount.",
         test_inputs=[([1,2,5], 11), ([2], 3), ([1], 0), ([1,3,4], 6)],
         reference_solution="def coin_change(coins, amount):\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for a in range(1, amount + 1):\n        for c in coins:\n            if c <= a:\n                dp[a] = min(dp[a], dp[a - c] + 1)\n    return dp[amount] if dp[amount] != float('inf') else -1\n",
         hints=["Think of building up the answer for every amount from 0 up to the target, using answers you've already computed for smaller amounts.",
                "For a given amount, try using each coin denomination as the LAST coin used: that leaves (amount - coin) to solve, which you've already computed. Take the best option across all coins.",
                "dp=[inf]*(amount+1); dp[0]=0; for a in 1..amount: for c in coins: if c<=a: dp[a]=min(dp[a], dp[a-c]+1). Return dp[amount] if finite else -1."]),

    dict(slug="unique-paths", title="Unique Paths", day=42, topic="dynamic-programming", pattern="2D DP", difficulty="Medium", interview_priority="Important", estimated_solve_minutes=25, progression_stage="variation", canonical_reference="LeetCode 62: Unique Paths",
         description="A robot starts at the top-left of an m x n grid and can only move right or down. Return the number of unique paths to the bottom-right corner.",
         constraints="1 <= m, n <= 100.",
         function_signature="def unique_paths(m, n):",
         starter_code="def unique_paths(m, n):\n    pass\n",
         expected_time_complexity="O(m*n)", expected_space_complexity="O(m*n) (can be reduced to O(n))",
         brute_force_approach="Naive recursion trying both moves (right/down) at every cell -- exponential, heavy overlap.",
         optimal_approach="dp[i][j] = dp[i-1][j] + dp[i][j-1] -- the number of ways to reach a cell is the sum of ways to reach the cell above and the cell to the left.",
         common_mistakes="Forgetting the first row/column must be initialized to 1 (only one way to reach them: a straight line); indexing dp[i][j] with i,j swapped relative to rows/cols.",
         edge_cases="m=1 or n=1 (exactly 1 path -- a straight line); m=n=1 (trivially 1 path, already there).",
         test_inputs=[(3, 7), (3, 2), (1, 1), (1, 5)],
         reference_solution="def unique_paths(m, n):\n    dp = [[1] * n for _ in range(m)]\n    for i in range(1, m):\n        for j in range(1, n):\n            dp[i][j] = dp[i-1][j] + dp[i][j-1]\n    return dp[m-1][n-1]\n",
         hints=["Every cell can only be reached by moving right (from the cell to its left) or down (from the cell above it) -- so the number of ways to reach it is the sum of ways to reach those two cells.",
                "The entire first row and first column only have one possible path each: a straight line of rights or a straight line of downs.",
                "dp = 2D grid of 1s sized m x n; for i in 1..m-1, for j in 1..n-1: dp[i][j] = dp[i-1][j] + dp[i][j-1]. Return dp[m-1][n-1]."]),
    # ---- Added to close real curriculum-promised gaps and give the
    # highest-frequency interview patterns (linked lists, trees, hashing,
    # queues, graph DFS) an easy-before-medium pair rather than a single
    # data point. See docs/problem-roadmap.md "Progression design" for why
    # this set of 6 was chosen over a full concept->easy->easy->medium->
    # medium-variation ladder across all 15 patterns (scope tradeoff,
    # documented rather than silently shipped as if it were complete).

    dict(slug="merge-two-sorted-lists", title="Merge Two Sorted Lists", day=26, topic="linked-lists",
         pattern="dummy-head merge", difficulty="Easy", interview_priority="Core",
         estimated_solve_minutes=15, progression_stage="core", canonical_reference="LeetCode 21: Merge Two Sorted Lists",
         description="Merge two sorted linked lists into one sorted linked list by splicing their nodes together, and return the head. Lists are represented as plain Python lists here for testing; your function receives them as lists.",
         constraints="0 <= length of each list <= 50; both lists are sorted in non-decreasing order.",
         function_signature="def merge_two_lists(l1_values, l2_values):",
         starter_code="class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None\n\ndef build_list(values):\n    head = None\n    for v in reversed(values):\n        node = Node(v)\n        node.next = head\n        head = node\n    return head\n\ndef to_list(head):\n    result = []\n    while head:\n        result.append(head.val)\n        head = head.next\n    return result\n\ndef merge_two_lists(l1_values, l2_values):\n    # Build real linked lists from l1_values/l2_values, merge them by\n    # splicing nodes (don't just concatenate-and-sort the values), then\n    # convert the result back to a plain list to return.\n    l1 = build_list(l1_values)\n    l2 = build_list(l2_values)\n    pass\n",
         expected_time_complexity="O(n + m)", expected_space_complexity="O(1) extra (excluding the lists themselves)",
         brute_force_approach="Collect all values into one Python list, sort it, rebuild a linked list -- works but is O((n+m) log(n+m)) and ignores that both inputs are already sorted.",
         optimal_approach="Use a dummy head node and a tail pointer; repeatedly attach whichever current node (from l1 or l2) has the smaller value, then advance that list's pointer.",
         common_mistakes="Forgetting to attach whichever list still has leftover nodes after the other is exhausted; comparing values but forgetting to actually advance the pointer of the list you took from.",
         edge_cases="One list is empty; both lists are empty; lists of very different lengths; duplicate values across lists.",
         test_inputs=[([1,2,4],[1,3,4]), ([],[]), ([],[0]), ([1,3,5],[2,4]), ([5],[1,2,3])],
         reference_solution="class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None\n\ndef build_list(values):\n    head = None\n    for v in reversed(values):\n        node = Node(v)\n        node.next = head\n        head = node\n    return head\n\ndef to_list(head):\n    result = []\n    while head:\n        result.append(head.val)\n        head = head.next\n    return result\n\ndef merge_two_lists(l1_values, l2_values):\n    l1 = build_list(l1_values)\n    l2 = build_list(l2_values)\n    dummy = Node(0)\n    tail = dummy\n    while l1 and l2:\n        if l1.val <= l2.val:\n            tail.next = l1\n            l1 = l1.next\n        else:\n            tail.next = l2\n            l2 = l2.next\n        tail = tail.next\n    tail.next = l1 if l1 else l2\n    return to_list(dummy.next)\n",
         hints=["You don't need to sort anything -- both lists are already sorted, so you can build the merged list by always taking whichever list's current node is smaller, one node at a time.",
                "Use a dummy placeholder node as the start of your result and a 'tail' pointer that always points to the last node you've attached -- this avoids annoying special-casing for the very first node.",
                "dummy = Node(0); tail = dummy; while l1 and l2: attach the smaller of l1/l2 to tail.next, advance that list and tail. When the loop ends, one list may still have nodes left -- attach whichever one directly (tail.next = l1 or l2). Return dummy.next converted back to a list."]),

    dict(slug="linked-list-cycle-detection", title="Linked List Cycle Detection", day=27, topic="linked-lists",
         pattern="Floyd's slow/fast pointer", difficulty="Easy", interview_priority="Core",
         estimated_solve_minutes=15, progression_stage="variation", canonical_reference="LeetCode 141: Linked List Cycle",
         description="Given a linked list (as a list of values) and a position `pos` where the tail connects back to (forming a cycle), or -1 for no cycle, determine whether the list has a cycle.",
         constraints="0 <= length <= 10^4; -1 <= pos < length.",
         function_signature="def has_cycle(values, pos):",
         starter_code="class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None\n\ndef has_cycle(values, pos):\n    # Build the list, connecting the tail's .next to nodes[pos] if pos != -1.\n    if not values:\n        return False\n    nodes = [Node(v) for v in values]\n    for i in range(len(nodes) - 1):\n        nodes[i].next = nodes[i + 1]\n    if pos != -1:\n        nodes[-1].next = nodes[pos]\n    # Use two pointers moving at different speeds to detect a cycle\n    # WITHOUT storing every visited node (that would work too, but the\n    # point of this problem is the O(1)-space two-pointer technique).\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(1)",
         brute_force_approach="Store every visited node in a set; if you ever revisit a node, there's a cycle -- correct, but O(n) extra space.",
         optimal_approach="Floyd's tortoise and hare: a slow pointer moves 1 step, a fast pointer moves 2 steps. If there's a cycle, they will eventually land on the same node; if the fast pointer reaches the end (None), there's no cycle.",
         common_mistakes="Checking fast.next.next without first checking fast.next is not None (crashes on odd-length non-cyclic lists); comparing node VALUES instead of node IDENTITY (two different nodes can hold equal values).",
         edge_cases="Empty list (pos=-1, no cycle possible); single node with no cycle; single node that cycles to itself (pos=0); cycle starting partway through the list.",
         test_inputs=[([3,2,0,-4], 1), ([1,2], 0), ([1], -1), ([1,2,3], -1), ([1], 0)],
         reference_solution="class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None\n\ndef has_cycle(values, pos):\n    if not values:\n        return False\n    nodes = [Node(v) for v in values]\n    for i in range(len(nodes) - 1):\n        nodes[i].next = nodes[i + 1]\n    if pos != -1:\n        nodes[-1].next = nodes[pos]\n    slow = fast = nodes[0]\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow is fast:\n            return True\n    return False\n",
         hints=["Imagine two runners on a track: if the track has a loop, a faster runner will eventually lap the slower one and they'll be at the same spot again. If the track is a straight line, the faster runner just reaches the end first.",
                "Move a 'slow' pointer one node at a time and a 'fast' pointer two nodes at a time. If they're ever pointing at the exact same node object, there's a cycle. If 'fast' (or fast.next) hits None, there isn't.",
                "slow = fast = head; while fast and fast.next: slow = slow.next; fast = fast.next.next; if slow is fast: return True. After the loop exits normally (fast ran off the end): return False."]),

    dict(slug="max-depth-binary-tree", title="Maximum Depth of Binary Tree", day=30, topic="trees",
         pattern="DFS recursion", difficulty="Easy", interview_priority="Core",
         estimated_solve_minutes=15, progression_stage="core", canonical_reference="LeetCode 104: Maximum Depth of Binary Tree",
         description="Given the root of a binary tree (as a level-order list with `None` for missing children, e.g. [3,9,20,None,None,15,7]), return its maximum depth (the number of nodes along the longest path from root to a leaf).",
         constraints="0 <= number of nodes <= 10^4.",
         function_signature="def max_depth(values):",
         starter_code="class TreeNode:\n    def __init__(self, val):\n        self.val = val\n        self.left = None\n        self.right = None\n\ndef build_tree(values):\n    if not values or values[0] is None:\n        return None\n    root = TreeNode(values[0])\n    queue = [root]\n    i = 1\n    while queue and i < len(values):\n        node = queue.pop(0)\n        if i < len(values):\n            lv = values[i]; i += 1\n            if lv is not None:\n                node.left = TreeNode(lv)\n                queue.append(node.left)\n        if i < len(values):\n            rv = values[i]; i += 1\n            if rv is not None:\n                node.right = TreeNode(rv)\n                queue.append(node.right)\n    return root\n\ndef max_depth(values):\n    root = build_tree(values)\n    # A tree's depth is 1 (for the current node) plus the deeper of its\n    # two subtrees' depths. What's the depth of an empty tree (None)?\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(h) for the recursion stack, where h is the tree's height",
         brute_force_approach="There isn't really a separate 'brute force' here -- the recursive definition IS the efficient solution. An iterative BFS level-by-level count is an equally valid O(n) alternative.",
         optimal_approach="Recursive DFS: depth(node) = 0 if node is None, else 1 + max(depth(node.left), depth(node.right)).",
         common_mistakes="Forgetting the base case (None returns 0, not 1); using min() instead of max() (that computes minimum depth to any leaf, a different problem).",
         edge_cases="Empty tree (root is None); single node; a completely lopsided tree (effectively a linked list) to make sure recursion depth is handled correctly.",
         test_inputs=[([3,9,20,None,None,15,7],), ([],), ([1],), ([1,None,2],), ([1,2,3,4],)],
         reference_solution="class TreeNode:\n    def __init__(self, val):\n        self.val = val\n        self.left = None\n        self.right = None\n\ndef build_tree(values):\n    if not values or values[0] is None:\n        return None\n    root = TreeNode(values[0])\n    queue = [root]\n    i = 1\n    while queue and i < len(values):\n        node = queue.pop(0)\n        if i < len(values):\n            lv = values[i]; i += 1\n            if lv is not None:\n                node.left = TreeNode(lv)\n                queue.append(node.left)\n        if i < len(values):\n            rv = values[i]; i += 1\n            if rv is not None:\n                node.right = TreeNode(rv)\n                queue.append(node.right)\n    return root\n\ndef max_depth(values):\n    root = build_tree(values)\n    def depth(node):\n        if node is None:\n            return 0\n        return 1 + max(depth(node.left), depth(node.right))\n    return depth(root)\n",
         hints=["A tree's depth is naturally recursive: the depth of the whole tree is 1 (for the root) plus whichever of its two subtrees goes deeper.",
                "What should an empty tree (a None node) return as its depth? That's your base case -- get it right and the recursive case falls out easily.",
                "def depth(node): if node is None: return 0; return 1 + max(depth(node.left), depth(node.right))."]),

    dict(slug="sliding-window-maximum", title="Sliding Window Maximum", day=29, topic="queues",
         pattern="monotonic deque", difficulty="Medium", interview_priority="Core",
         estimated_solve_minutes=30, progression_stage="core", canonical_reference="LeetCode 239: Sliding Window Maximum",
         description="Given an array `nums` and a window size `k`, return an array of the maximum value in each contiguous window of size k as it slides from left to right.",
         constraints="1 <= k <= len(nums) <= 10^5.",
         function_signature="def max_sliding_window(nums, k):",
         starter_code="from collections import deque\n\ndef max_sliding_window(nums, k):\n    # Keep a deque of INDICES such that the values at those indices are\n    # always in decreasing order -- the front is always the current max.\n    pass\n",
         expected_time_complexity="O(n)", expected_space_complexity="O(k)",
         brute_force_approach="For each window, scan all k elements to find the max -- O(n*k), too slow for large inputs.",
         optimal_approach="A monotonic deque of indices: before adding a new index, pop from the back any indices whose values are smaller than the new value (they can never be the max again). Pop from the front any index that's fallen out of the current window.",
         common_mistakes="Storing values in the deque instead of indices (you need indices to know when something falls out of the window); forgetting to pop smaller elements from the back before appending, which breaks the decreasing-order invariant.",
         edge_cases="k equals the whole array length (one output value); k=1 (output equals the input); strictly increasing or strictly decreasing input.",
         test_inputs=[([1,3,-1,-3,5,3,6,7], 3), ([1], 1), ([9,11], 2), ([4,-2], 2), ([1,3,1,2,0,5], 3)],
         reference_solution="from collections import deque\n\ndef max_sliding_window(nums, k):\n    dq = deque()\n    result = []\n    for i, n in enumerate(nums):\n        while dq and nums[dq[-1]] < n:\n            dq.pop()\n        dq.append(i)\n        if dq[0] <= i - k:\n            dq.popleft()\n        if i >= k - 1:\n            result.append(nums[dq[0]])\n    return result\n",
         hints=["You don't need to rescan the whole window every time -- most of the previous window's information is still useful for the next window. What can you reuse?",
                "Keep a deque of INDICES where the corresponding values are in decreasing order from front to back. Before pushing a new index, remove any indices from the back whose values are smaller than the new one -- they'll never be the max of any future window.",
                "For each i: pop smaller values from the deque's back, then append i. If the front index has fallen out of the window (dq[0] <= i - k), pop it from the front. Once i >= k-1, the front of the deque is the current window's max -- append nums[dq[0]] to the result."]),

    dict(slug="max-area-of-island", title="Max Area of Island", day=37, topic="graphs",
         pattern="grid DFS / flood fill", difficulty="Medium", interview_priority="Important",
         estimated_solve_minutes=25, progression_stage="variation", canonical_reference="LeetCode 695: Max Area of Island",
         description="Given a grid of 0s (water) and 1s (land), an island is a group of 1s connected 4-directionally. Return the area of the largest island (0 if there is no land).",
         constraints="1 <= rows, cols <= 50.",
         function_signature="def max_area_of_island(grid):",
         starter_code="def max_area_of_island(grid):\n    rows, cols = len(grid), len(grid[0]) if grid else 0\n    visited = set()\n\n    def dfs(r, c):\n        # Return the area of the island reachable from (r, c), marking\n        # cells visited so you don't count them twice or loop forever.\n        pass\n\n    best = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == 1 and (r, c) not in visited:\n                best = max(best, dfs(r, c))\n    return best\n",
         expected_time_complexity="O(rows * cols)", expected_space_complexity="O(rows * cols) worst case for the recursion stack / visited set",
         brute_force_approach="There isn't a meaningfully different brute force -- every cell must be looked at at least once. The key insight to get right is avoiding double-counting or infinite loops via a visited set.",
         optimal_approach="DFS (or BFS) flood-fill from every unvisited land cell, counting connected 1s in each direction, tracking the max area seen.",
         common_mistakes="Forgetting to mark cells visited BEFORE recursing into neighbors (causes infinite recursion on cycles); not checking grid bounds before indexing (index error at the edges).",
         edge_cases="All water (answer 0); all land (one big island); a grid with several separate islands of different sizes; a 1x1 grid.",
         test_inputs=[([[0,0,1,0,0,0,0,1,0,0,0,0,0],[0,0,0,0,0,0,0,1,1,1,0,0,0],[0,1,1,0,1,0,0,0,0,0,0,0,0],[0,1,0,0,1,1,0,0,1,0,1,0,0],[0,1,0,0,1,1,0,0,1,1,1,0,0],[0,0,0,0,0,0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,1,1,1,0,0,0],[0,0,0,0,0,0,0,1,1,0,0,0,0]],), ([[0,0,0],[0,0,0]],), ([[1]],), ([[1,1],[1,1]],)],
         reference_solution="def max_area_of_island(grid):\n    rows, cols = len(grid), len(grid[0]) if grid else 0\n    visited = set()\n\n    def dfs(r, c):\n        if r < 0 or r >= rows or c < 0 or c >= cols:\n            return 0\n        if (r, c) in visited or grid[r][c] == 0:\n            return 0\n        visited.add((r, c))\n        return 1 + dfs(r + 1, c) + dfs(r - 1, c) + dfs(r, c + 1) + dfs(r, c - 1)\n\n    best = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == 1 and (r, c) not in visited:\n                best = max(best, dfs(r, c))\n    return best\n",
         hints=["This is the same 'explore connected territory' idea as counting islands, except instead of just counting how many islands exist, you need to measure how big each one is.",
                "Write a DFS helper that, starting from a land cell, marks it visited and returns 1 (for itself) plus the sum of what its four neighbors' DFS calls return. Water cells and out-of-bounds cells contribute 0.",
                "def dfs(r, c): if out of bounds or visited or water: return 0; mark (r,c) visited; return 1 + dfs in all 4 directions. In the main loop, call dfs on every unvisited land cell and track the max result."]),

    dict(slug="group-anagrams", title="Group Anagrams", day=11, topic="hashing",
         pattern="hashmap of sorted-string keys", difficulty="Medium", interview_priority="Core",
         estimated_solve_minutes=25, progression_stage="variation", canonical_reference="LeetCode 49: Group Anagrams",
         description="Given an array of strings, group the anagrams together (strings that use exactly the same letters with the same counts). Return the groups in any order, and the strings within each group in any order.",
         constraints="1 <= len(strs) <= 10^4; strings contain only lowercase English letters.",
         function_signature="def group_anagrams(strs):",
         starter_code="def group_anagrams(strs):\n    # Two strings are anagrams iff they produce the same string once sorted.\n    # Use that sorted string as a hashmap key to bucket anagrams together.\n    pass\n",
         expected_time_complexity="O(n * k log k) where k is the max string length", expected_space_complexity="O(n * k)",
         brute_force_approach="Compare every string against every other string to check if they're anagrams -- O(n^2 * k), way too slow for large inputs.",
         optimal_approach="For each string, compute a canonical key (its letters sorted into a fixed order). Strings that are anagrams of each other produce the identical key, so group them in a hashmap keyed by that.",
         common_mistakes="Using the unsorted string as the key (defeats the purpose -- anagrams would get different keys); forgetting that the ORDER of groups and of strings within a group doesn't matter for correctness.",
         edge_cases="A single string; a string that has no anagram partners in the list; the empty string \"\" (its sorted form is also \"\", so multiple empty strings group together); all strings are anagrams of each other.",
         test_inputs=[(["eat","tea","tan","ate","nat","bat"],), ([""],), (["a"],), (["abc","bca","cab","xyz"],)],
         reference_solution="def group_anagrams(strs):\n    groups = {}\n    for s in strs:\n        key = \"\".join(sorted(s))\n        groups.setdefault(key, []).append(s)\n    return list(groups.values())\n",
         hints=["Two words are anagrams of each other exactly when sorting their letters produces the same result. That sorted result can act as a shared 'bucket label'.",
                "Build a dict mapping this canonical sorted-letters key to a list of original strings that share it. Every string with the same key belongs in the same group.",
                "groups = {}; for s in strs: key = ''.join(sorted(s)); groups.setdefault(key, []).append(s). Return list(groups.values())."],
         comparison_mode="unordered_list_of_sorted_lists"),
]

assert len({p["slug"] for p in PROBLEMS}) == len(PROBLEMS), "Duplicate problem slugs"
