"""
Real lesson content for all 45 curriculum days, adapted from
docs/45-day-curriculum.md (the source of truth). Not placeholders --
every field below is genuine content, condensed for a lesson page rather
than the full interactive teaching-loop dialogue (which happens in
conversation with a tutor, not as static page text).

Days 1-7 content is adapted from study-notes/days-01-07-study-guide.md,
which was already written in full prose for this curriculum.
"""

LESSONS = [
    dict(day=1, title="Variables, print, data types, input, comments",
         block="Python Fundamentals",
         python_concepts="Variables & assignment, print(), core types (int/float/str/bool), input(), comments (#)",
         dsa_concepts="What DSA is; re-anchoring your existing Big-O intuition as vocabulary we'll use daily",
         why="You can't reason about algorithms without writing and running instructions. Naming Big-O vocabulary on Day 1 means every later day can use it naturally.",
         visual="A variable as a labeled box holding a value -- the label doesn't change, its contents do.",
         example_code='name = input("What\'s your name? ")\nage = int(input("What\'s your age? "))\nprint("Hello, " + name)\nprint(age + 1)',
         prediction_question='What does this print?\n\nx = 3\nx = 3 + 2\nprint(x)',
         prediction_answer="5 -- Python evaluates the right side (3+2=5) fully, then stores it, overwriting the old 3.",
         exercises="Print a greeting.\nStore name+age in variables, print a sentence using both.\nSwap two variables' values.\nCelsius-to-Fahrenheit converter (F = C*9/5+32).\nRead a number with input(), convert with int(), print it doubled.",
         must_explain="What a variable is; int/float/str/bool differences; what print()/input() do; what a comment is.",
         common_mistakes="Confusing = with ==; forgetting quotes around strings; mixing int and str in print (TypeError); inconsistent indentation.",
         minutes=200),
    dict(day=2, title="Operators, conditionals, booleans",
         block="Python Fundamentals",
         python_concepts="Arithmetic/comparison/logical operators, if/elif/else, truthiness",
         dsa_concepts="Conditionals as how algorithms make decisions -- foreshadows binary search/sorting comparisons",
         why="Almost every algorithm is 'loop + condition'. Fluency here is a prerequisite for everything else.",
         visual="A decision tree showing which if/elif/else branch fires for a given input.",
         example_code='age = 20\nif age < 13:\n    print("child")\nelif age < 20:\n    print("teen")\nelse:\n    print("adult")',
         prediction_question="If score = 85, which branch runs: `if score >= 90: A` / `elif score >= 80: B` / `else: F`?",
         prediction_answer="B -- Python checks top to bottom and runs the first True condition; 85 fails >=90 but passes >=80.",
         exercises="Even/odd checker.\nLargest of 3 numbers.\nGrade calculator via if/elif chain.\nLeap year checker.\nFizzBuzz-style checks on 5 hardcoded numbers.",
         must_explain="= vs ==; how elif chains evaluate top-to-bottom; and/or/not; truthy/falsy.",
         common_mistakes="Using = instead of == in a condition; forgetting colons; misordering elif branches; comparing floats for exact equality.",
         minutes=210),
    dict(day=3, title="Loops (the most important beginner concept)",
         block="Python Fundamentals",
         python_concepts="while, for, range(), break, continue, nested loops",
         dsa_concepts="Iteration as a core building block; loop count <-> time complexity (O(n) single loop, O(n^2) nested)",
         why="Array/string algorithms are built almost entirely from loops. This is the day complexity stops being abstract.",
         visual="A loop counter animating i from 0 to n-1 with a highlighted 'current position' -- literally the seed of the trace visualizer.",
         example_code='total = 0\nfor i in range(1, 6):   # 1,2,3,4,5\n    total = total + i\nprint(total)  # 15',
         prediction_question="How many times does `for i in range(5):` run, and what's the last value of i?",
         prediction_answer="5 times, i takes 0,1,2,3,4 -- range(5) is exclusive of 5 itself.",
         exercises="Print 1-10 with while, then for+range.\nSum of 1 to n.\nMultiplication table.\nCount vowels in a string with a loop.\nPrint a triangle of stars (nested loop).\nFactorial via loop; count digits; reverse a number arithmetically.",
         must_explain="while vs for; what range(a,b) generates; break vs continue; why nested loops multiply iteration count.",
         common_mistakes="Off-by-one with range(); infinite while loops from forgetting to update the condition variable; confusing break with continue.",
         minutes=240),
    dict(day=4, title="Lists (arrays)",
         block="Python Fundamentals",
         python_concepts="List creation, indexing (incl. negative), slicing, append/insert/pop/remove/len/in/sort/reverse",
         dsa_concepts="This IS the array data structure -- index, element, contiguous. Python lists are dynamic arrays.",
         why="Nearly every early DSA problem is 'do something to a list' -- the bridge from Python syntax to DSA problems.",
         visual="Array-as-boxes-in-a-row with index labels; what changes visually on append/pop/insert.",
         example_code='arr = [4, 7, 2, 9]\nbiggest = arr[0]\nfor x in arr:\n    if x > biggest:\n        biggest = x\nprint(biggest)  # 9',
         prediction_question="If arr = [10, 20, 30] and b = arr, then b.append(40) -- what does arr look like now?",
         prediction_answer="[10, 20, 30, 40] -- b and arr point to the SAME list (aliasing), not two separate copies.",
         exercises="Largest element (write it yourself, not max()).\nSecond largest element.\nSum of array; count of even numbers.\nReverse an array in place using a loop.",
         must_explain="0-based indexing and negative indices; what arr[a:b] returns; append vs insert; why b=a doesn't copy a list.",
         common_mistakes="Off-by-one on slicing; mutating a list while iterating it; assuming b=a copies the list (aliasing bug).",
         minutes=240),
    dict(day=5, title="Strings",
         block="Python Fundamentals",
         python_concepts="Indexing/slicing, immutability, split/join/strip/replace/upper/lower/find, f-strings",
         dsa_concepts="Strings as array-like-but-immutable -- sets up two-pointer/sliding-window work later",
         why="String manipulation is one of the most common interview categories; understanding immutability prevents a whole class of bugs.",
         visual="String-as-array-of-characters, same visual style as Day 4's array.",
         example_code='def is_palindrome(s):\n    left, right = 0, len(s) - 1\n    while left < right:\n        if s[left] != s[right]:\n            return False\n        left += 1\n        right -= 1\n    return True',
         prediction_question='What does sorted("cab") return -- a string or something else?',
         prediction_answer="A list: ['a','b','c']. sorted() always returns a list, even for a string input.",
         exercises="Reverse a string with a manual loop.\nPalindrome check.\nCount vowels/consonants.\nAnagram check (sort-and-compare).",
         must_explain="Why strings are immutable; what s[::-1] does mechanically; == vs is for strings.",
         common_mistakes="Trying to mutate a string in place; building strings with += in a loop without knowing the cost; case-sensitivity bugs.",
         minutes=240),
    dict(day=6, title="Functions",
         block="Python Fundamentals",
         python_concepts="def, parameters, default arguments, return vs print, local vs global scope",
         dsa_concepts="Functions are how every interview solution is structured (def twoSum(nums, target):)",
         why="From tomorrow, every problem is 'write a function that takes X, returns Y' -- the format of interview platforms and this app's automated testing.",
         visual="A function-call diagram: arguments flow in, a return value flows out, like a black box.",
         example_code='def max_of_two(a, b):\n    if a > b:\n        return a\n    return b',
         prediction_question="A function only has print(result) and no return statement. What does calling it and using the result give you?",
         prediction_answer="None -- print() displays but doesn't hand a value back to the caller; a function with no return implicitly returns None.",
         exercises="Function returning max of two numbers.\nFunction checking primality.\nRewrite largest-element, palindrome-check, anagram-check as proper functions.",
         must_explain="return vs print; what happens to a variable defined inside a function once it returns (scope).",
         common_mistakes="Using print() instead of return in a function meant to produce a value (breaks automated testing); not handling empty input.",
         minutes=240),
    dict(day=7, title="Dictionaries, sets, Week 1 checkpoint",
         block="Python Fundamentals",
         python_concepts="Dict creation, in, .get(), .keys()/.values()/.items(), sets",
         dsa_concepts="On-ramp to hashing (Day 11) -- a dict IS Python's hash map",
         why="Hashing is one of the highest-frequency interview patterns, and everything from here depends on dict/set fluency.",
         visual="Side-by-side: a list scanned linearly vs a dict looked up directly.",
         example_code='def has_duplicate(nums):\n    seen = set()\n    for n in nums:\n        if n in seen:\n            return True\n        seen.add(n)\n    return False',
         prediction_question='phonebook = {}; phonebook["Alex"] = "555"; print(phonebook.get("Bob"))  -- what prints?',
         prediction_answer="None -- .get() on a missing key returns None instead of raising KeyError.",
         exercises="Word-frequency counter using a dict.\nDuplicate check using a set.\nSimple phonebook: add/lookup/delete.\nTwo Sum, brute-force only.",
         must_explain="List membership vs dict/set membership mechanically; what a dict key must satisfy; [] vs .get() on a missing key.",
         common_mistakes="Using a list where a set fits better; KeyError instead of .get(); relying on dict ordering without knowing why it's guaranteed.",
         minutes=210),

    dict(day=8, title="Array patterns I: traversal & in-place modification",
         block="Arrays, Strings, Hashing",
         python_concepts="List comprehensions (intro), enumerate()",
         dsa_concepts="In-place modification, O(1) extra-space constraint, read/write pointer technique",
         why="enumerate/comprehensions are used in nearly every array solution from here; 'O(1) extra space' is a very common interview constraint.",
         visual="Array boxes with a read pointer and write pointer moving at different speeds during in-place removal.",
         example_code='def remove_duplicates(arr):\n    write = 1\n    for read in range(1, len(arr)):\n        if arr[read] != arr[write - 1]:\n            arr[write] = arr[read]\n            write += 1\n    return write',
         prediction_question="Given arr=[1,1,1,2,2,3], what does arr[:write] look like after remove_duplicates, and what does it return?",
         prediction_answer="arr[:3] == [1,2,3], returns 3.",
         exercises="See curated problems for Day 8 in the problem browser.",
         must_explain="What 'in-place'/'O(1) extra space' mean; how enumerate() replaces manual index tracking.",
         common_mistakes="Mutating a list mid-iteration with for x in arr; confusing reassignment with in-place mutation.",
         minutes=210),
    dict(day=9, title="Array patterns II: prefix sums",
         block="Arrays, Strings, Hashing",
         python_concepts="zip(), tuple unpacking",
         dsa_concepts="Prefix-sum technique for O(1) range-sum queries after O(n) precompute",
         why="First 'precompute now, save time later' lesson -- a very common optimization shape.",
         visual="A running-total bar building left-to-right beneath the array: prefix[i] = prefix[i-1] + arr[i].",
         example_code='def prefix_sums(arr):\n    prefix = [0] * len(arr)\n    prefix[0] = arr[0]\n    for i in range(1, len(arr)):\n        prefix[i] = prefix[i-1] + arr[i]\n    return prefix',
         prediction_question="arr=[2,4,1,3]. What is prefix[2]?",
         prediction_answer="7 (2+4+1)",
         exercises="See curated problems for Day 9.",
         must_explain="How prefix[i] derives from prefix[i-1]; why this gives O(1)-per-query after O(n) precompute.",
         common_mistakes="Off-by-one mapping a prefix index to the original range; mishandling index 0.",
         minutes=210),
    dict(day=10, title="Strings deep dive",
         block="Arrays, Strings, Hashing",
         python_concepts="''.join(), list(s), sorted() on strings",
         dsa_concepts="Character-comparison and character-frequency patterns",
         why="String problems recur constantly and nearly always reduce to 'compare characters' or 'count characters'.",
         visual="Two strings side by side, matches green / mismatches red; pointers converging for palindrome checks.",
         example_code='def is_anagram(a, b):\n    return sorted(a) == sorted(b)',
         prediction_question='Is "listen" an anagram of "silent"? Justify using sorted().',
         prediction_answer="Yes -- sorted('listen') == sorted('silent') == ['e','i','l','n','s','t'].",
         exercises="See curated problems for Day 10.",
         must_explain="Sort-based vs counting-based anagram check and their complexity tradeoff (O(n log n) vs O(n)).",
         common_mistakes="Ignoring case/whitespace/punctuation without being told to; assuming sorted() on a string returns a string.",
         minutes=210),
    dict(day=11, title="Hashing I: Two Sum pattern",
         block="Arrays, Strings, Hashing",
         python_concepts="Dict comprehensions, collections.defaultdict (intro)",
         dsa_concepts='"Have I seen this value/complement before?" -- the canonical hashing pattern',
         why="Two Sum's hash-map solution is the textbook example of trading space for time -- one of the most-asked patterns in existence.",
         visual="Array traversal with a live dict panel; a lookup flash when a complement is found.",
         example_code='def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        complement = target - n\n        if complement in seen:\n            return [seen[complement], i]\n        seen[n] = i\n    return []',
         prediction_question="Why check for the complement BEFORE inserting the current number into the dict, not after?",
         prediction_answer="To avoid using the same element twice as its own complement (e.g. target=6, nums=[3] shouldn't match 3 with itself unless another 3 exists).",
         exercises="See curated problems for Day 11.",
         must_explain="Why storing 'value seen so far -> index' gives O(1) complement lookup vs re-scanning; O(n) time/O(n) space tradeoff vs brute force.",
         common_mistakes="Checking for the complement after inserting the current element; reusing the same element twice.",
         minutes=240),
    dict(day=12, title="Hashing II: frequency & grouping",
         block="Arrays, Strings, Hashing",
         python_concepts="collections.Counter, sorting dict items by value",
         dsa_concepts="Frequency-map pattern, group-by-key pattern",
         why="'Count occurrences then decide' is the second core hashing pattern.",
         visual="Bar-chart-style frequency panel updating live as elements are scanned.",
         example_code='from collections import Counter\ndef top_k_frequent(nums, k):\n    counts = Counter(nums)\n    return [x for x, _ in counts.most_common(k)]',
         prediction_question="Why can't a list be used as a dict key for grouping anagrams, but a tuple can?",
         prediction_answer="Dict keys must be hashable (immutable); lists are mutable so unhashable, tuples aren't.",
         exercises="See curated problems for Day 12.",
         must_explain="How a sorted-tuple/frequency-tuple can serve as a dict key for grouping.",
         common_mistakes="Using a mutable type as a dict key; off-by-one between 'first' and 'any' unique element.",
         minutes=240),
    dict(day=13, title="Two pointers I: opposite-direction on sorted data",
         block="Arrays, Strings, Hashing",
         python_concepts="None new -- pattern-focused",
         dsa_concepts="Two-pointer technique on sorted arrays",
         why="Converts many O(n^2) brute forces into O(n); one of the most-tested placement patterns.",
         visual="Two arrows (left, right) moving toward each other on the array.",
         example_code='def two_sum_sorted(nums, target):\n    left, right = 0, len(nums) - 1\n    while left < right:\n        s = nums[left] + nums[right]\n        if s == target:\n            return [left, right]\n        elif s < target:\n            left += 1\n        else:\n            right -= 1\n    return []',
         prediction_question="If the current sum is LESS than target, which pointer should move, and why?",
         prediction_answer="Move left forward (increase the sum) -- since the array is sorted, moving right would only decrease or keep the sum, never help reach a bigger target.",
         exercises="See curated problems for Day 13.",
         must_explain="Why two pointers needs sorted data; how to decide which pointer to move.",
         common_mistakes="Forgetting to sort first; pointers crossing incorrectly or missing the last valid pair.",
         minutes=210),
    dict(day=14, title="Two pointers II: same-direction / container problems",
         block="Arrays, Strings, Hashing",
         python_concepts="None new",
         dsa_concepts="Same-direction two pointers, greedy pointer movement",
         why="This variant reappears in linked-list problems (Day 27).",
         visual="Two vertical wall bars, shaded area between them shrinking as the shorter wall moves inward.",
         example_code='def max_area(height):\n    left, right = 0, len(height) - 1\n    best = 0\n    while left < right:\n        area = (right - left) * min(height[left], height[right])\n        best = max(best, area)\n        if height[left] < height[right]:\n            left += 1\n        else:\n            right -= 1\n    return best',
         prediction_question="Why move the pointer at the SHORTER wall, never the taller one?",
         prediction_answer="Width can only shrink as pointers move inward, so the only way area might improve is if the limiting (shorter) height increases -- moving the taller wall can never help.",
         exercises="See curated problems for Day 14.",
         must_explain="The greedy justification for moving the shorter wall's pointer.",
         common_mistakes="Moving the taller wall; off-by-one on width calculation.",
         minutes=210),
    dict(day=15, title="Sliding window I: fixed size",
         block="Arrays, Strings, Hashing",
         python_concepts="None new",
         dsa_concepts="Fixed-size sliding window -- incremental update instead of recompute",
         why="Natural next step after prefix sums and two pointers.",
         visual="A highlighted window rectangle sliding across the array, sum updating incrementally.",
         example_code='def max_sum_subarray(arr, k):\n    window_sum = sum(arr[:k])\n    best = window_sum\n    for i in range(k, len(arr)):\n        window_sum += arr[i] - arr[i - k]\n        best = max(best, window_sum)\n    return best',
         prediction_question="Why is `window_sum += arr[i] - arr[i-k]` faster than recomputing sum(window) every step?",
         prediction_answer="It's O(1) per step instead of O(k), giving O(n) total instead of O(n*k).",
         exercises="See curated problems for Day 15.",
         must_explain="Why incremental window updates are O(1) per step vs O(k) recomputation.",
         common_mistakes="Recomputing the full window sum every slide; off-by-one on window boundaries.",
         minutes=210),
    dict(day=16, title="Sliding window II: variable size; Block 2 checkpoint",
         block="Arrays, Strings, Hashing",
         python_concepts="None new",
         dsa_concepts="Variable-size sliding window (grow/shrink based on a condition)",
         why="The more powerful, more commonly tested sliding-window variant, combining with Days 11-12's hashing.",
         visual="Window rectangle that grows right / shrinks left independently, with a dict panel of in-window counts.",
         example_code='def longest_unique_substring(s):\n    seen = {}\n    left = 0\n    best = 0\n    for right, ch in enumerate(s):\n        if ch in seen and seen[ch] >= left:\n            left = seen[ch] + 1\n        seen[ch] = right\n        best = max(best, right - left + 1)\n    return best',
         prediction_question="For s='abba', trace left/right pointers -- what's the longest unique-character substring length?",
         prediction_answer="2 ('ab' or 'ba') -- the second 'b' forces left to jump past the first 'b'.",
         exercises="See curated problems for Day 16. Block 2 checkpoint: revisit one problem each from Days 8-15.",
         must_explain="The grow/shrink invariant -- when to expand right vs contract left.",
         common_mistakes="Shrinking with if instead of while; updating 'best answer' at the wrong point relative to shrinking.",
         minutes=240),

    dict(day=17, title="Sorting I: bubble sort, selection sort",
         block="Sorting, Binary Search, Recursion",
         python_concepts="Tuple-swap (a, b = b, a)",
         dsa_concepts="Comparison-based sorting, stability concept (intro)",
         why="Simplest sorts to implement/reason about -- the first 'algorithm as a sequence of comparisons/swaps'.",
         visual="Bar-chart array, two bars highlighted (comparing), then animated swap, pass by pass.",
         example_code='def bubble_sort(arr):\n    n = len(arr)\n    for i in range(n):\n        swapped = False\n        for j in range(n - i - 1):\n            if arr[j] > arr[j+1]:\n                arr[j], arr[j+1] = arr[j+1], arr[j]\n                swapped = True\n        if not swapped:\n            break\n    return arr',
         prediction_question="What does the `swapped` flag optimize for?",
         prediction_answer="Early exit -- if a full pass makes no swaps, the array is already sorted, so we can stop instead of doing all n passes.",
         exercises="Implement bubble sort and selection sort; count swaps/comparisons each makes.",
         must_explain="How bubble sort's bubbling works pass by pass; both are O(n^2)/O(1).",
         common_mistakes="Skipping the early-exit optimization; off-by-one in inner-loop bounds.",
         minutes=210),
    dict(day=18, title="Sorting II: insertion sort, built-in sort",
         block="Sorting, Binary Search, Recursion",
         python_concepts="sorted(iterable, key=..., reverse=...), list.sort()",
         dsa_concepts="Insertion sort mechanics; when Timsort (built-in, O(n log n)) is appropriate",
         why="Insertion sort bridges to merge sort; key= fluency is used constantly in real interview code.",
         visual="A growing 'sorted portion' as each new element is inserted at its correct position.",
         example_code='def insertion_sort(arr):\n    for i in range(1, len(arr)):\n        key = arr[i]\n        j = i - 1\n        while j >= 0 and arr[j] > key:\n            arr[j+1] = arr[j]\n            j -= 1\n        arr[j+1] = key\n    return arr',
         prediction_question="sorted([('b',2), ('a',3)], key=lambda t: t[1]) -- which comes first?",
         prediction_answer="('b',2) -- sorted by the second element ascending, so 2 before 3.",
         exercises="Implement insertion sort; sort tuples by second element with key=.",
         must_explain="Why insertion sort is efficient (adaptive) on nearly-sorted data despite O(n^2) worst case.",
         common_mistakes="arr = arr.sort() (returns None); backwards key= lambda.",
         minutes=210),
    dict(day=19, title="Sorting III: merge sort", block="Sorting, Binary Search, Recursion",
         python_concepts="None new (recursion used practically before Day 23 formalizes it)",
         dsa_concepts="Divide-and-conquer, merge step, O(n log n)",
         why="The jump from O(n^2) to O(n log n) is the most important complexity lesson in the curriculum.",
         visual="Recursive split diagram (halving to single elements) then a merge-back-up zippering two sorted halves.",
         example_code='def merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\n\ndef merge(left, right):\n    result, i, j = [], 0, 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i]); i += 1\n        else:\n            result.append(right[j]); j += 1\n    return result + left[i:] + right[j:]',
         prediction_question="Why does halving repeatedly give log n levels?",
         prediction_answer="Each level halves the size; after log2(n) halvings you reach size 1 -- same reasoning as binary search.",
         exercises="Implement the merge step alone, then full merge sort.",
         must_explain="Why each level does O(n) total merge work and there are O(log n) levels, giving O(n log n).",
         common_mistakes="Off-by-one on the midpoint; missing base case causing infinite recursion.",
         minutes=240),
    dict(day=20, title="Sorting IV: quicksort", block="Sorting, Binary Search, Recursion",
         python_concepts="None new",
         dsa_concepts="Partition-based divide-and-conquer, pivot choice, average vs worst case",
         why="The most commonly discussed sort in interviews; partition logic reappears in quickselect-style problems.",
         visual="Pivot highlighted, elements sliding left/right of it as compared.",
         example_code='def quicksort(arr):\n    if len(arr) <= 1:\n        return arr\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    mid = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quicksort(left) + mid + quicksort(right)',
         prediction_question="What input makes quicksort degrade to O(n^2) if you always pick the first element as pivot?",
         prediction_answer="An already-sorted (or reverse-sorted) array -- every partition is maximally unbalanced.",
         exercises="Implement partition alone, then full quicksort.",
         must_explain="Why average case is O(n log n) but worst case is O(n^2); why random/median pivot mitigates this.",
         common_mistakes="Infinite loop from incorrect partition pointer movement; mishandling duplicates.",
         minutes=240),
    dict(day=21, title="Binary search I: classic", block="Sorting, Binary Search, Recursion",
         python_concepts="None new",
         dsa_concepts="O(log n) search",
         why="Appears constantly, directly and as a sub-pattern ('binary search the answer').",
         visual="Sorted array with low/mid/high pointers; search space shrinking by half each step.",
         example_code='def binary_search(arr, target):\n    low, high = 0, len(arr) - 1\n    while low <= high:\n        mid = low + (high - low) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1',
         prediction_question="Why `low + (high-low)//2` instead of `(low+high)//2`?",
         prediction_answer="Overflow safety in languages with fixed-width integers (not a Python issue, but expected interview knowledge).",
         exercises="Implement binary search iteratively, then recursively.",
         must_explain="Why the data must be sorted; why this is O(log n).",
         common_mistakes="low<=high vs low<high confusion; off-by-one on low=mid+1/high=mid-1.",
         minutes=210),
    dict(day=22, title="Binary search II: variants", block="Sorting, Binary Search, Recursion",
         python_concepts="None new",
         dsa_concepts="Binary search on modified conditions; 'binary search the answer' (intro)",
         why="Real interview binary-search questions are almost always a variant, not the textbook version.",
         visual="Same halving visual applied to a 'rotated' array.",
         example_code='def search_rotated(nums, target):\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[lo] <= nums[mid]:\n            if nums[lo] <= target < nums[mid]:\n                hi = mid - 1\n            else:\n                lo = mid + 1\n        else:\n            if nums[mid] < target <= nums[hi]:\n                lo = mid + 1\n            else:\n                hi = mid - 1\n    return -1',
         prediction_question="In a rotated array, how do you tell which half is sorted?",
         prediction_answer="Compare nums[lo] to nums[mid]: if nums[lo] <= nums[mid], the left half is sorted; otherwise the right half is.",
         exercises="First/last occurrence with duplicates; search in a rotated sorted array.",
         must_explain="How to modify the base template to keep searching after a match.",
         common_mistakes="Returning too early on first match; wrong condition for identifying the sorted half.",
         minutes=240),
    dict(day=23, title="Recursion I: call stack, base case (take your time)", block="Sorting, Binary Search, Recursion",
         python_concepts="Functions calling themselves -- formal recursion rules",
         dsa_concepts="Recursion as a paradigm -- a major beginner hurdle, given a full unhurried day",
         why="Recursion underlies trees, backtracking, and DP -- arguably the hardest concept in the curriculum.",
         visual="The recursion-tree/call-stack visualizer -- stacked boxes appearing as calls deepen, popping as base cases resolve.",
         example_code='def factorial(n):\n    if n <= 1:       # base case\n        return 1\n    return n * factorial(n - 1)  # recursive case',
         prediction_question="Why is naive recursive Fibonacci O(2^n)?",
         prediction_answer="Each call branches into two more calls (fib(n-1) and fib(n-2)) with almost no overlap avoided, so the call tree roughly doubles in size each level.",
         exercises="Factorial (recursive); sum of first n numbers (recursive); naive recursive Fibonacci -- trace by hand first.",
         must_explain="What a base case is and why every recursive function needs one; what happens on the call stack as calls deepen then return.",
         common_mistakes="Missing/incorrect base case -> infinite recursion/RecursionError; discarding the recursive call's return value.",
         minutes=240),
    dict(day=24, title="Recursion II: branching recursion, intro backtracking; Block 3 checkpoint", block="Sorting, Binary Search, Recursion",
         python_concepts="None new",
         dsa_concepts="Multiple recursive calls per invocation; backtracking as 'recursion + undo'",
         why="Bridges into tree/graph traversal; backtracking is a common interview topic on its own.",
         visual="A branching recursion tree (2+ children per node) for generating subsets of a 3-element set.",
         example_code='def subsets(nums):\n    result = []\n    def backtrack(start, path):\n        result.append(path[:])\n        for i in range(start, len(nums)):\n            path.append(nums[i])\n            backtrack(i + 1, path)\n            path.pop()\n    backtrack(0, [])\n    return result',
         prediction_question="Why must path.append(...) be paired with path.pop() after the recursive call?",
         prediction_answer="To 'undo' the choice before trying the next branch -- without popping, later branches would incorrectly include earlier choices.",
         exercises="Generate all subsets of a small set; generate all permutations of a small set.",
         must_explain="The choose/explore/un-choose backtracking pattern; why subset count is 2^n.",
         common_mistakes="Forgetting to copy the current path before saving it to results; not undoing a choice before the next branch.",
         minutes=240),

    dict(day=25, title="Linked lists I: nodes, references, traversal", block="Linked Lists, Stacks, Queues, Trees",
         python_concepts="Classes (class, __init__, self) -- first real OOP",
         dsa_concepts="Node + next-pointer structure; contrast with arrays",
         why="First 'build your own data structure' topic, and where the trace visualizer becomes essential.",
         visual="Boxes connected by arrows (node -> next -> node -> next -> None).",
         example_code='class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None\n\ndef print_list(head):\n    current = head\n    while current:\n        print(current.val)\n        current = current.next',
         prediction_question="If you move `current` forward without saving `head`, can you still get back to the start of the list?",
         prediction_answer="No -- head still points to the first node (it wasn't reassigned), but if you'd overwritten head itself instead of using a separate current pointer, you would lose access.",
         exercises="Define a Node class; build a 4-node list by hand; traverse-and-print; compute length.",
         must_explain="What self refers to; what .next actually stores.",
         common_mistakes="Losing the head reference by reassigning it during traversal; forgetting the final node's .next must be None.",
         minutes=240),
    dict(day=26, title="Linked lists II: insertion, deletion", block="Linked Lists, Stacks, Queues, Trees",
         python_concepts="None new",
         dsa_concepts="Pointer rewiring for insert/delete at head/tail/middle/by-value",
         why="Where linked lists' O(1)-insertion advantage over arrays becomes concrete.",
         visual="Arrow-rewiring animation -- old arrow fading, new arrow appearing.",
         example_code='def insert_at_head(head, val):\n    new_node = Node(val)\n    new_node.next = head\n    return new_node',
         prediction_question="Why is inserting at the head O(1) but inserting at the tail O(n) without a tail pointer?",
         prediction_answer="Head insertion just rewires one pointer; tail insertion requires traversing the whole list first to find the last node.",
         exercises="Insert at head/tail/after a node; delete by value; delete the head.",
         must_explain="The exact operation order needed to avoid losing the rest of the list.",
         common_mistakes="Overwriting a .next before saving the reference it pointed to; not special-casing head deletion.",
         minutes=240),
    dict(day=27, title="Linked lists III: reversal, cycle detection", block="Linked Lists, Stacks, Queues, Trees",
         python_concepts="None new",
         dsa_concepts="In-place reversal; Floyd's cycle detection (fast/slow)",
         why="Reverse-a-linked-list is one of the most-asked interview questions everywhere.",
         visual="Reversal via three pointers (prev, curr, next); cycle detection as two pointers meeting inside a loop.",
         example_code='def reverse_list(head):\n    prev = None\n    curr = head\n    while curr:\n        nxt = curr.next\n        curr.next = prev\n        prev = curr\n        curr = nxt\n    return prev',
         prediction_question="Why save `nxt = curr.next` before doing `curr.next = prev`?",
         prediction_answer="Because curr.next = prev overwrites the link to the rest of the list -- without saving it first, you'd lose access to everything after curr.",
         exercises="Reverse a list iteratively; implement Floyd's cycle detection.",
         must_explain="The three-pointer reversal mechanics step by step; why fast/slow pointers must eventually meet if a cycle exists.",
         common_mistakes="Losing the rest of the list by not saving next first; using a set to detect cycles (defeats the O(1)-space point).",
         minutes=240),
    dict(day=28, title="Stacks", block="Linked Lists, Stacks, Queues, Trees",
         python_concepts="List as a stack (append/pop), or collections.deque",
         dsa_concepts="LIFO structure and its canonical uses",
         why="Simple to implement but powers a disproportionate number of interview problems.",
         visual="A vertical stack of plates -- push adds to top, pop removes from top.",
         example_code='def is_valid_parens(s):\n    stack = []\n    pairs = {")": "(", "]": "[", "}": "{"}\n    for ch in s:\n        if ch in "([{":\n            stack.append(ch)\n        elif ch in pairs:\n            if not stack or stack.pop() != pairs[ch]:\n                return False\n    return not stack',
         prediction_question="Why check `not stack` at the very end, not just during the loop?",
         prediction_answer="To catch unmatched OPENING brackets left over, e.g. '(()' passes the loop fine but leaves one '(' unclosed.",
         exercises="Implement a stack with a list; Valid Parentheses.",
         must_explain="Why LIFO order is exactly what nested-structure matching needs.",
         common_mistakes="Popping from an empty stack (IndexError); forgetting to check the stack is empty at the end.",
         minutes=210),
    dict(day=29, title="Queues", block="Linked Lists, Stacks, Queues, Trees",
         python_concepts="collections.deque (popleft, appendleft, O(1) both ends)",
         dsa_concepts="FIFO structure; why deque over a plain list",
         why="Queues are the backbone of BFS (Day 36).",
         visual="A horizontal line, new items entering right, served from left.",
         example_code='from collections import deque\nq = deque()\nq.append(1)\nq.append(2)\nprint(q.popleft())  # 1 -- FIFO',
         prediction_question="Why is list.pop(0) O(n) but deque.popleft() O(1)?",
         prediction_answer="Removing from the front of a list requires shifting every remaining element down one index; a deque is structured to avoid that.",
         exercises="Implement a queue with deque; Implement Queue using two Stacks.",
         must_explain="FIFO vs LIFO, compared directly to stacks.",
         common_mistakes="Using a plain list with pop(0) in performance-sensitive code.",
         minutes=210),
    dict(day=30, title="Trees I: structure, traversals", block="Linked Lists, Stacks, Queues, Trees",
         python_concepts="None new -- reuses classes and recursion",
         dsa_concepts="Binary tree structure; preorder/inorder/postorder traversal",
         why="Trees are where recursion and node/reference structures combine.",
         visual="A small binary tree with nodes highlighting in visit order per traversal type.",
         example_code='class TreeNode:\n    def __init__(self, val):\n        self.val = val\n        self.left = None\n        self.right = None\n\ndef inorder(node, result):\n    if not node:\n        return\n    inorder(node.left, result)\n    result.append(node.val)\n    inorder(node.right, result)',
         prediction_question="For a BST, what special property does inorder traversal have?",
         prediction_answer="It visits values in sorted order.",
         exercises="Define TreeNode; build a small tree by hand; implement all three traversals.",
         must_explain="The difference between the three traversal orders.",
         common_mistakes="Swapping the order of recursive calls vs the visit step; missing the None-node base case.",
         minutes=240),
    dict(day=31, title="Trees II: Binary Search Trees", block="Linked Lists, Stacks, Queues, Trees",
         python_concepts="None new",
         dsa_concepts="BST ordering invariant",
         why="BSTs connect trees back to binary search.",
         visual="BST diagram shading the valid region for where a new value can go.",
         example_code='def insert_bst(node, val):\n    if not node:\n        return TreeNode(val)\n    if val < node.val:\n        node.left = insert_bst(node.left, val)\n    else:\n        node.right = insert_bst(node.right, val)\n    return node',
         prediction_question="Why is checking only immediate children NOT enough to validate a BST?",
         prediction_answer="A node deep in the left subtree must be less than ALL its ancestors on the path, not just its direct parent -- the valid range is inherited, not just locally checked.",
         exercises="Implement BST insertion and search; validate a BST.",
         must_explain="The BST invariant applies to the entire subtree, not just immediate children.",
         common_mistakes="Validating a BST by only checking immediate children.",
         minutes=240),
    dict(day=32, title="Trees III: height, level order; Block 4 checkpoint", block="Linked Lists, Stacks, Queues, Trees",
         python_concepts="None new -- reuses deque",
         dsa_concepts="Height/depth calculation; level-order (BFS) traversal",
         why="Level-order traversal is the direct conceptual predecessor to graph BFS (Day 36).",
         visual="The tree shown level by level with a queue panel showing dequeues/enqueues.",
         example_code='from collections import deque\ndef level_order(root):\n    if not root:\n        return []\n    result, queue = [], deque([root])\n    while queue:\n        node = queue.popleft()\n        result.append(node.val)\n        if node.left: queue.append(node.left)\n        if node.right: queue.append(node.right)\n    return result',
         prediction_question="Why does level-order traversal need a queue specifically, not a stack?",
         prediction_answer="A queue processes nodes in the order they were discovered (FIFO), which naturally produces level-by-level order; a stack would process the most recently discovered node next, producing a depth-first order instead.",
         exercises="Recursive height/max-depth; level-order traversal.",
         must_explain="Why level-order needs a queue; how height is computed bottom-up.",
         common_mistakes="Forgetting to track level boundaries when output must be grouped by level.",
         minutes=240),

    dict(day=33, title="Heaps I: concept, heapq", block="Heaps, Graphs",
         python_concepts="heapq (heappush, heappop, heapify)",
         dsa_concepts="Heap/priority-queue structure -- partial ordering, not full sorting",
         why="Solves 'give me the smallest/largest repeatedly' more efficiently than re-sorting every time.",
         visual="Binary-tree-shaped heap next to its array representation; contrast with a BST.",
         example_code='import heapq\nheap = []\nheapq.heappush(heap, 5)\nheapq.heappush(heap, 1)\nheapq.heappush(heap, 3)\nprint(heapq.heappop(heap))  # 1 -- min-heap',
         prediction_question="How do you simulate a max-heap using Python's min-heap-only heapq?",
         prediction_answer="Push negated values (-x), and negate again when popping.",
         exercises="Push 6 values, trace bubble-up by hand; implement kth smallest element.",
         must_explain="The heap invariant (parent <= children for min-heap) -- NOT the same as BST ordering.",
         common_mistakes="Confusing heap ordering with BST ordering (siblings aren't ordered).",
         minutes=210),
    dict(day=34, title="Heaps II: top-K pattern", block="Heaps, Graphs",
         python_concepts="None new",
         dsa_concepts="Top-K via a size-bounded heap",
         why="'Top K' is an extremely common interview family.",
         visual="A size-limited heap where each new element competes against the current worst for a spot.",
         example_code='import heapq\ndef top_k(nums, k):\n    heap = []\n    for n in nums:\n        heapq.heappush(heap, n)\n        if len(heap) > k:\n            heapq.heappop(heap)\n    return heap',
         prediction_question="Why does bounding the heap to size k give O(n log k) instead of O(n log n)?",
         prediction_answer="Each push/pop is O(log k) (heap size never exceeds k) rather than O(log n) for a heap holding all n elements.",
         exercises="Top-K frequent elements via heap; K Closest Points to Origin.",
         must_explain="Why bounding the heap to size k gives O(n log k).",
         common_mistakes="Forgetting to pop when the heap exceeds size k.",
         minutes=210),
    dict(day=35, title="Graphs I: representation & terminology", block="Heaps, Graphs",
         python_concepts="Dict-of-lists as adjacency list",
         dsa_concepts="Vertices/edges, directed vs undirected, adjacency list vs matrix",
         why="A tree is just a graph with no cycles -- graphs generalize what you already know.",
         visual="A small graph drawn as nodes-and-edges, then as an adjacency list and matrix side by side.",
         example_code='def build_graph(edges):\n    graph = {}\n    for a, b in edges:\n        graph.setdefault(a, []).append(b)\n        graph.setdefault(b, []).append(a)  # undirected\n    return graph',
         prediction_question="Why must an undirected edge be added to BOTH nodes' adjacency lists?",
         prediction_answer="Because undirected means you can travel either direction; adding it only one way would make it effectively directed.",
         exercises="Build an adjacency list from an edge list; convert list<->matrix by hand.",
         must_explain="When adjacency list beats adjacency matrix (sparse vs dense).",
         common_mistakes="Forgetting to add the edge both directions for undirected graphs.",
         minutes=210),
    dict(day=36, title="Graphs II: BFS", block="Heaps, Graphs",
         python_concepts="None new -- reuses deque",
         dsa_concepts="Graph BFS -- shortest path in unweighted graphs, visited-set tracking",
         why="Direct generalization of Day 32's tree level-order to graphs, plus a visited set for cycles.",
         visual="Same queue-and-highlighting style as tree BFS, now with a visited overlay.",
         example_code='from collections import deque\ndef bfs(graph, start):\n    visited = {start}\n    queue = deque([start])\n    order = []\n    while queue:\n        node = queue.popleft()\n        order.append(node)\n        for neighbor in graph.get(node, []):\n            if neighbor not in visited:\n                visited.add(neighbor)\n                queue.append(neighbor)\n    return order',
         prediction_question="Why mark a node visited at ENQUEUE time, not dequeue time?",
         prediction_answer="If you wait until dequeue, the same node could be enqueued multiple times by different neighbors before it's ever processed, wasting work (and in some variants causing incorrect results).",
         exercises="Trace BFS by hand on a cyclic graph; implement BFS from a start node.",
         must_explain="Why the visited set is mandatory in graph BFS but wasn't needed for tree BFS.",
         common_mistakes="Forgetting the visited set (infinite loop on cycles).",
         minutes=240),
    dict(day=37, title="Graphs III: DFS", block="Heaps, Graphs",
         python_concepts="None new",
         dsa_concepts="Graph DFS -- recursive vs explicit-stack iterative, connected components",
         why="BFS's natural counterpart; reinforces Day 23's call-stack lesson with an explicit stack.",
         visual="The same graph as Day 36, explored depth-first -- one path plunging deep before backtracking.",
         example_code='def dfs(graph, start, visited=None):\n    if visited is None:\n        visited = set()\n    visited.add(start)\n    order = [start]\n    for neighbor in graph.get(start, []):\n        if neighbor not in visited:\n            order += dfs(graph, neighbor, visited)\n    return order',
         prediction_question="On the same graph, do BFS and DFS always visit nodes in the same order?",
         prediction_answer="No -- BFS spreads level by level, DFS plunges deep first; they usually differ in order but both correctly visit every reachable node.",
         exercises="Trace DFS on the same graph used for BFS and compare; implement DFS recursively and iteratively.",
         must_explain="Recursive DFS's implicit call-stack use vs the iterative version's explicit stack.",
         common_mistakes="Missing the visited check in recursive DFS (infinite recursion on cycles).",
         minutes=240),
    dict(day=38, title="Shortest paths: Dijkstra; Block 5 checkpoint", block="Heaps, Graphs",
         python_concepts="None new -- reuses heapq",
         dsa_concepts="Weighted shortest-path problem; Dijkstra's greedy + heap approach",
         why="The capstone combining graphs, heaps, and BFS's level-by-level intuition.",
         visual="Graph exploration with weighted edges and a running 'shortest distance so far' table.",
         example_code='import heapq\ndef dijkstra(graph, start):\n    dist = {start: 0}\n    heap = [(0, start)]\n    while heap:\n        d, node = heapq.heappop(heap)\n        if d > dist.get(node, float("inf")):\n            continue\n        for neighbor, weight in graph.get(node, []):\n            nd = d + weight\n            if nd < dist.get(neighbor, float("inf")):\n                dist[neighbor] = nd\n                heapq.heappush(heap, (nd, neighbor))\n    return dist',
         prediction_question="Why skip a node if `d > dist.get(node, inf)` when popped from the heap?",
         prediction_answer="That entry is stale -- a shorter path to that node was already found and pushed later; the old, longer entry is now obsolete.",
         exercises="Trace Dijkstra by hand on a 5-node weighted graph; implement it with heapq.",
         must_explain="Why plain BFS fails on weighted graphs; why the heap always expands the closest unvisited node next.",
         common_mistakes="Using a plain queue instead of a heap (silently wrong, not crashing).",
         minutes=250),

    dict(day=39, title="DP I: overlapping subproblems, memoization vs tabulation", block="Dynamic Programming",
         python_concepts="functools.lru_cache (after building a memo dict by hand first)",
         dsa_concepts="What gives a problem DP structure; top-down vs bottom-up",
         why="The payoff for Day 23's 'naive Fibonacci is slow' cliffhanger.",
         visual="The Day 23 Fibonacci recursion tree, now with repeated subtrees grayed out once memoized.",
         example_code='def fib_memo(n, memo={}):\n    if n in memo:\n        return memo[n]\n    if n <= 1:\n        return n\n    memo[n] = fib_memo(n-1, memo) + fib_memo(n-2, memo)\n    return memo[n]',
         prediction_question="Why does memoization bring Fibonacci from O(2^n) down to O(n)?",
         prediction_answer="Each distinct subproblem (each value of n) is computed only once and then reused, instead of being recomputed exponentially many times.",
         exercises="Time naive Fibonacci at n=30; add memoization and re-time; rewrite bottom-up.",
         must_explain="The mechanical difference between top-down (recursion+cache) and bottom-up (iterative fill).",
         common_mistakes="Memoizing with a mutable default argument without understanding it persists across calls; off-by-one in tabulation array sizing.",
         minutes=240),
    dict(day=40, title="DP II: 1D DP (decision at each step)", block="Dynamic Programming",
         python_concepts="None new",
         dsa_concepts="1D DP where each state depends on a small, fixed number of previous states",
         why="House Robber's dp[i]=max(dp[i-1], dp[i-2]+val) recurrence generalizes to many interview questions.",
         visual="A 1D table filling left to right, arrows from dp[i-1]/dp[i-2] into dp[i].",
         example_code='def house_robber(nums):\n    prev2, prev1 = 0, 0\n    for n in nums:\n        prev2, prev1 = prev1, max(prev1, prev2 + n)\n    return prev1',
         prediction_question="Why can't House Robber be solved greedily (always take the bigger of the next two houses)?",
         prediction_answer="A locally-bigger choice can block a much better combination later; you can construct examples where greedy underperforms the true optimum.",
         exercises="State the recurrence in plain English first; implement House Robber and Min Cost Climbing Stairs.",
         must_explain="How to derive a recurrence from a plain-language problem description.",
         common_mistakes="Writing code before stating the recurrence in words; off-by-one on base cases.",
         minutes=240),
    dict(day=41, title="DP III: coin change, LIS intro", block="Dynamic Programming",
         python_concepts="None new",
         dsa_concepts="Minimization DP (coin change); sequence DP (LIS, O(n^2))",
         why="Coin change introduces 'try every choice, take the best'; LIS is one of the most iconic DP questions.",
         visual="A table showing which previous cells were checked across denominations before taking the min.",
         example_code='def coin_change(coins, amount):\n    dp = [float("inf")] * (amount + 1)\n    dp[0] = 0\n    for a in range(1, amount + 1):\n        for c in coins:\n            if c <= a:\n                dp[a] = min(dp[a], dp[a - c] + 1)\n    return dp[amount] if dp[amount] != float("inf") else -1',
         prediction_question="Why initialize dp[1:] to infinity rather than 0?",
         prediction_answer="0 would incorrectly suggest 'reachable with 0 coins' for every amount; infinity correctly represents 'not yet known to be reachable' before taking a min.",
         exercises="Implement coin change (minimum coins); implement LIS in O(n^2).",
         must_explain="Why coin change tries every denomination at each amount instead of a fixed lookback.",
         common_mistakes="Not initializing unreachable amounts to infinity before taking a min.",
         minutes=240),
    dict(day=42, title="DP IV: 2D DP intro; Block 6 checkpoint", block="Dynamic Programming",
         python_concepts="None new",
         dsa_concepts="2D DP (state depends on two dimensions)",
         why="The final new concept of the core curriculum -- depth over breadth for a 45-day timeline.",
         visual="A 2D grid table filling in reading order, arrows from the cell(s) above/left it depends on.",
         example_code='def unique_paths(m, n):\n    dp = [[1] * n for _ in range(m)]\n    for i in range(1, m):\n        for j in range(1, n):\n            dp[i][j] = dp[i-1][j] + dp[i][j-1]\n    return dp[m-1][n-1]',
         prediction_question="Why is the first row and first column of the grid initialized to all 1s?",
         prediction_answer="There's exactly one way to reach any cell in the first row or column: keep moving in a single direction the whole way.",
         exercises="State the 2D recurrence in plain English first; implement Unique Paths.",
         must_explain="How a 2D table cell depends on specific neighbors (above/left).",
         common_mistakes="Incorrect first-row/first-column base-case initialization.",
         minutes=240),

    dict(day=43, title="Full revision day", block="Revision & Mock Interviews",
         python_concepts="None new",
         dsa_concepts="None new -- entirely revision, driven by tracked weak topics",
         why="Skills fade without deliberate revisit -- a full sweep before mock interviews.",
         visual="Whichever visualizations correspond to your specific weak topics.",
         example_code="", prediction_question="", prediction_answer="",
         exercises="Re-solve one problem from each of the 6 block checkpoints (Days 7,16,24,32,38,42) from scratch, prioritizing your weakest topics per the dashboard.",
         must_explain="For each revised topic, restate the core pattern/recurrence/invariant from memory.",
         common_mistakes="Whatever your tracker shows most frequently -- treated as the day's content.",
         minutes=240),
    dict(day=44, title="Mock interviews 1 and 2", block="Revision & Mock Interviews",
         python_concepts="None new", dsa_concepts="None new -- interview conditions (timer, no hints)",
         why="Solving under a clock while narrating your thinking is a different skill from solving alone.",
         visual="Mock-interview mode: minimal UI, timer, problem, editor only.",
         example_code="", prediction_question="", prediction_answer="",
         exercises="Two full mock interviews (30-45 min each) via Mock Interview Mode, followed by the post-interview review each time.",
         must_explain="A full walkthrough of your approach after each interview, as if speaking to an interviewer.",
         common_mistakes="Whatever the post-interview review surfaces.",
         minutes=240),
    dict(day=45, title="Mock interview 3, final review, wrap-up", block="Revision & Mock Interviews",
         python_concepts="None new", dsa_concepts="None new",
         why="One final mock interview, then an honest, data-backed look back at the full 45 days.",
         visual="The dashboard's final view -- problems solved, independent-solve rate, topics mastered vs weak.",
         example_code="", prediction_question="", prediction_answer="",
         exercises="One final mock interview (Medium); write a short self-assessment of your 3 strongest topics and 2-3 to keep practicing, checked against the dashboard.",
         must_explain="An honest, data-backed self-assessment, and a concrete post-Day-45 practice plan.",
         common_mistakes="Whatever the final mock interview surfaces.",
         minutes=210),
]

assert len(LESSONS) == 45, f"Expected 45 lessons, got {len(LESSONS)}"
assert [l["day"] for l in LESSONS] == list(range(1, 46)), "Lesson days must be 1..45 in order"
